source ~/.bashrc
source /home/xieyi/anaconda3/bin/activate mmat

# # adv50000 cat cle50000
# # PreActResNet50 patchmixup beta(1,1) against FGSM (eps=0.1)
# CUDA_VISIBLE_DEVICES=1 python -u tasklauncher-20220905.py run --mode defense --defense_mode patchmixup --mix_mode maskmixup --sample_mode bernoullisampler --attack_mode fgsm --attack_eps 0.1 --blackbox --exp_name preactresnet50-svhn --cla_model preactresnet50 --cla_network_pkl /home/data/maggie/result-newhome/train/cla-train/preactresnet50-svhn/20220627/00001-testacc-95.76/train-svhn-dataset/standard-trained-classifier-preactresnet50-on-clean-svhn-epoch-0013.pkl --dataset svhn --test_adv_dataset /home/data/maggie/result-newhome/attack/fgsm/preactresnet50-svhn/20220628/00002-fgsm-eps-0.1-acc-60.02/attack-svhn-dataset/samples/test --batch_size 256 --epochs 40 --lr 0.01 >> /home/maggie/mmat/log/SVHN/defense/patch-mixup-training/preactresnet50-svhn-patchmixup-fgsm-20220913.log 2>&1

# # PreActResNet50 patchmixup beta(1,1) against FGSM (eps=0.1)
# CUDA_VISIBLE_DEVICES=1 python -u tasklauncher-20220905.py run --mode defense --defense_mode patchmixup --mix_mode maskmixup --sample_mode bernoullisampler --attack_mode fgsm --attack_eps 0.1 --blackbox --exp_name preactresnet50-svhn --cla_model preactresnet50 --cla_network_pkl /home/data/maggie/result-newhome/train/cla-train/preactresnet50-svhn/20220627/00001-testacc-95.76/train-svhn-dataset/standard-trained-classifier-preactresnet50-on-clean-svhn-epoch-0013.pkl --dataset svhn --test_adv_dataset /home/data/maggie/result-newhome/attack/fgsm/preactresnet50-svhn/20220628/00002-fgsm-eps-0.1-acc-60.02/attack-svhn-dataset/samples/test --batch_size 256 --epochs 40 --lr 0.01 >> /home/maggie/mmat/log/SVHN/defense/patch-mixup-training/preactresnet50-svhn-patchmixup-fgsm-20220913.log 2>&1

# # PreActResNet50 patchmixup beta(1,1) against FGSM (eps=0.1)
# CUDA_VISIBLE_DEVICES=1 python -u tasklauncher-20220905.py run --mode defense --defense_mode patchmixup --mix_mode maskmixup --sample_mode bernoullisampler --attack_mode fgsm --attack_eps 0.1 --blackbox --exp_name preactresnet50-svhn --cla_model preactresnet50 --cla_network_pkl /home/data/maggie/result-newhome/train/cla-train/preactresnet50-svhn/20220627/00001-testacc-95.76/train-svhn-dataset/standard-trained-classifier-preactresnet50-on-clean-svhn-epoch-0013.pkl --dataset svhn --test_adv_dataset /home/data/maggie/result-newhome/attack/fgsm/preactresnet50-svhn/20220628/00002-fgsm-eps-0.1-acc-60.02/attack-svhn-dataset/samples/test --batch_size 256 --epochs 40 --lr 0.01 >> /home/maggie/mmat/log/SVHN/defense/patch-mixup-training/preactresnet50-svhn-patchmixup-fgsm-20220913.log 2>&1

# # PreActResNet50 patchmixup beta(1,1) against FGSM (eps=0.1)
# CUDA_VISIBLE_DEVICES=1 python -u tasklauncher-20220905.py run --mode defense --defense_mode patchmixup --mix_mode maskmixup --sample_mode bernoullisampler --attack_mode fgsm --attack_eps 0.1 --blackbox --exp_name preactresnet50-svhn --cla_model preactresnet50 --cla_network_pkl /home/data/maggie/result-newhome/train/cla-train/preactresnet50-svhn/20220627/00001-testacc-95.76/train-svhn-dataset/standard-trained-classifier-preactresnet50-on-clean-svhn-epoch-0013.pkl --dataset svhn --test_adv_dataset /home/data/maggie/result-newhome/attack/fgsm/preactresnet50-svhn/20220628/00002-fgsm-eps-0.1-acc-60.02/attack-svhn-dataset/samples/test --batch_size 256 --epochs 40 --lr 0.01 >> /home/maggie/mmat/log/SVHN/defense/patch-mixup-training/preactresnet50-svhn-patchmixup-fgsm-20220913.log 2>&1

# # PreActResNet50 patchmixup beta(1,1) against FGSM (eps=0.1)
# CUDA_VISIBLE_DEVICES=1 python -u tasklauncher-20220905.py run --mode defense --defense_mode patchmixup --mix_mode maskmixup --sample_mode bernoullisampler --attack_mode fgsm --attack_eps 0.1 --blackbox --exp_name preactresnet50-svhn --cla_model preactresnet50 --cla_network_pkl /home/data/maggie/result-newhome/train/cla-train/preactresnet50-svhn/20220627/00001-testacc-95.76/train-svhn-dataset/standard-trained-classifier-preactresnet50-on-clean-svhn-epoch-0013.pkl --dataset svhn --test_adv_dataset /home/data/maggie/result-newhome/attack/fgsm/preactresnet50-svhn/20220628/00002-fgsm-eps-0.1-acc-60.02/attack-svhn-dataset/samples/test --batch_size 256 --epochs 40 --lr 0.01 >> /home/maggie/mmat/log/SVHN/defense/patch-mixup-training/preactresnet50-svhn-patchmixup-fgsm-20220913.log 2>&1

# # PreActResNet50 patchmixup beta(1,1) against FGSM (eps=0.1)
# CUDA_VISIBLE_DEVICES=1 python -u tasklauncher-20220905.py run --mode defense --defense_mode patchmixup --mix_mode maskmixup --sample_mode bernoullisampler --attack_mode fgsm --attack_eps 0.1 --blackbox --exp_name preactresnet50-svhn --cla_model preactresnet50 --cla_network_pkl /home/data/maggie/result-newhome/train/cla-train/preactresnet50-svhn/20220627/00001-testacc-95.76/train-svhn-dataset/standard-trained-classifier-preactresnet50-on-clean-svhn-epoch-0013.pkl --dataset svhn --test_adv_dataset /home/data/maggie/result-newhome/attack/fgsm/preactresnet50-svhn/20220628/00002-fgsm-eps-0.1-acc-60.02/attack-svhn-dataset/samples/test --batch_size 256 --epochs 40 --lr 0.01 >> /home/maggie/mmat/log/SVHN/defense/patch-mixup-training/preactresnet50-svhn-patchmixup-fgsm-20220913.log 2>&1


#-------------以上要存储at训练好的模型-----------
# #   使用PGD对抗训练后的 cla1
# PreActResNet50 patchmixup beta(1,1) against pgd (eps=0.1)
CUDA_VISIBLE_DEVICES=1 python -u tasklauncher-20220905.py run --mode defense --defense_mode patchmixup --mix_mode maskmixup --sample_mode bernoullisampler --attack_mode pgd --attack_eps 0.1 --blackbox --exp_name preactresnet50-svhn --cla_model preactresnet50 --cla_network_pkl /home/data/maggie/result-newhome/defense/patchmixup/fgsm/maskmixup-bernoullisampler/preactresnet50-svhn/blackbox/20220909/00000/patchmixup-svhn-dataset/patchmixup-trained-classifier-preactresnet50-on-svhn-epoch-0008-patch-cla1.pkl --dataset svhn --test_adv_dataset /home/data/maggie/result-newhome/attack/pgd/preactresnet50-svhn/20220629/00002-pgd-eps-0.1-acc-35.61/attack-svhn-dataset/samples/test --batch_size 256 --epochs 40 --lr 0.01 >> /home/maggie/mmat/log/SVHN/defense/patch-mixup-training/preactresnet50-svhn-patchmixup-pgd-20220913.log 2>&1

# PreActResNet50 patchmixup beta(1,1) against autoattack (eps=0.1)
CUDA_VISIBLE_DEVICES=1 python -u tasklauncher-20220905.py run --mode defense --defense_mode patchmixup --mix_mode maskmixup --sample_mode bernoullisampler --attack_mode autoattack --attack_eps 0.1 --blackbox --exp_name preactresnet50-svhn --cla_model preactresnet50 --cla_network_pkl /home/data/maggie/result-newhome/defense/patchmixup/fgsm/maskmixup-bernoullisampler/preactresnet50-svhn/blackbox/20220909/00000/patchmixup-svhn-dataset/patchmixup-trained-classifier-preactresnet50-on-svhn-epoch-0008-patch-cla1.pkl --dataset svhn --test_adv_dataset /home/data/maggie/result-newhome/attack/autoattack/preactresnet50-svhn/20220728/00000-autoattack-eps-0.1-acc-29.94/attack-svhn-dataset/samples/test --batch_size 256 --epochs 40 --lr 0.01 >> /home/maggie/mmat/log/SVHN/defense/patch-mixup-training/preactresnet50-svhn-patchmixup-autoattack-20220913.log 2>&1

# PreActResNet50 patchmixup beta(1,1) against deepfool (eps=0.1)
CUDA_VISIBLE_DEVICES=1 python -u tasklauncher-20220905.py run --mode defense --defense_mode patchmixup --mix_mode maskmixup --sample_mode bernoullisampler --attack_mode deepfool --attack_eps 0.1 --blackbox --exp_name preactresnet50-svhn --cla_model preactresnet50 --cla_network_pkl /home/data/maggie/result-newhome/defense/patchmixup/fgsm/maskmixup-bernoullisampler/preactresnet50-svhn/blackbox/20220909/00000/patchmixup-svhn-dataset/patchmixup-trained-classifier-preactresnet50-on-svhn-epoch-0008-patch-cla1.pkl --dataset svhn --test_adv_dataset /home/data/maggie/result-newhome/attack/deepfool/preactresnet50-svhn/20220721/00000-deepfool-eps-0.1-acc-23.72/attack-svhn-dataset/samples/test --batch_size 256 --epochs 40 --lr 0.01 >> /home/maggie/mmat/log/SVHN/defense/patch-mixup-training/preactresnet50-svhn-patchmixup-deepfool-20220913.log 2>&1

# PreActResNet50 patchmixup beta(1,1) against cw (eps=0.1)
CUDA_VISIBLE_DEVICES=1 python -u tasklauncher-20220905.py run --mode defense --defense_mode patchmixup --mix_mode maskmixup --sample_mode bernoullisampler --attack_mode cw --attack_eps 0.1 --blackbox --exp_name preactresnet50-svhn --cla_model preactresnet50 --cla_network_pkl /home/data/maggie/result-newhome/defense/patchmixup/fgsm/maskmixup-bernoullisampler/preactresnet50-svhn/blackbox/20220909/00000/patchmixup-svhn-dataset/patchmixup-trained-classifier-preactresnet50-on-svhn-epoch-0008-patch-cla1.pkl --dataset svhn --test_adv_dataset /home/data/maggie/result-newhome/attack/cw/preactresnet50-svhn/20220807/00000-cw-confidence-0.0-acc-27.09/attack-svhn-dataset/samples/test --batch_size 256 --epochs 40 --lr 0.01 >> /home/maggie/mmat/log/SVHN/defense/patch-mixup-training/preactresnet50-svhn-patchmixup-cw-20220913.log 2>&1

# PreActResNet50 patchmixup beta(1,1) against om-fgsm (eps=0.1)
CUDA_VISIBLE_DEVICES=1 python -u tasklauncher-20220905.py run --mode defense --defense_mode patchmixup --mix_mode maskmixup --sample_mode bernoullisampler --attack_mode om-fgsm --attack_eps 0.1 --blackbox --exp_name preactresnet50-svhn --cla_model preactresnet50 --cla_network_pkl /home/data/maggie/result-newhome/defense/patchmixup/fgsm/maskmixup-bernoullisampler/preactresnet50-svhn/blackbox/20220909/00000/patchmixup-svhn-dataset/patchmixup-trained-classifier-preactresnet50-on-svhn-epoch-0008-patch-cla1.pkl --dataset svhn --test_adv_dataset /home/data/maggie/result-newhome/attack/fgsm/preactresnet50-svhn/20220710/00002-omfgsm-eps-0.1-acc-40.01/attack-svhn-dataset/latent-attack-samples/test --batch_size 256 --epochs 40 --lr 0.01 >> /home/maggie/mmat/log/SVHN/defense/patch-mixup-training/preactresnet50-svhn-patchmixup-om-fgsm-20220913.log 2>&1

# PreActResNet50 patchmixup beta(1,1) against om-pgd (eps=0.1)
CUDA_VISIBLE_DEVICES=1 python -u tasklauncher-20220905.py run --mode defense --defense_mode patchmixup --mix_mode maskmixup --sample_mode bernoullisampler --attack_mode om-pgd --attack_eps 0.1 --blackbox --exp_name preactresnet50-svhn --cla_model preactresnet50 --cla_network_pkl /home/data/maggie/result-newhome/defense/patchmixup/fgsm/maskmixup-bernoullisampler/preactresnet50-svhn/blackbox/20220909/00000/patchmixup-svhn-dataset/patchmixup-trained-classifier-preactresnet50-on-svhn-epoch-0008-patch-cla1.pkl --dataset svhn --test_adv_dataset /home/data/maggie/result-newhome/attack/pgd/preactresnet50-svhn/20220713/00002-ompgd-eps-0.1-acc-6.73/attack-svhn-dataset/latent-attack-samples/test --batch_size 256 --epochs 40 --lr 0.01 >> /home/maggie/mmat/log/SVHN/defense/patch-mixup-training/preactresnet50-svhn-patchmixup-om-pgd-20220913.log 2>&1

# #   使用PGD对抗训练后的 cla2
# PreActResNet50 patchmixup beta(1,1) against pgd (eps=0.1)
CUDA_VISIBLE_DEVICES=1 python -u tasklauncher-20220905.py run --mode defense --defense_mode patchmixup --mix_mode maskmixup --sample_mode bernoullisampler --attack_mode pgd --attack_eps 0.1 --blackbox --exp_name preactresnet50-svhn --cla_model preactresnet50 --cla_network_pkl /home/data/maggie/result-newhome/defense/patchmixup/fgsm/maskmixup-bernoullisampler/preactresnet50-svhn/blackbox/20220911/00004/patchmixup-svhn-dataset/patchmixup-trained-classifier-preactresnet50-on-svhn-epoch-0007-patch-cla2.pkl --dataset svhn --test_adv_dataset /home/data/maggie/result-newhome/attack/pgd/preactresnet50-svhn/20220629/00002-pgd-eps-0.1-acc-35.61/attack-svhn-dataset/samples/test --batch_size 256 --epochs 40 --lr 0.01 >> /home/maggie/mmat/log/SVHN/defense/patch-mixup-training/preactresnet50-svhn-patchmixup-pgd-20220913.log 2>&1

# PreActResNet50 patchmixup beta(1,1) against autoattack (eps=0.1)
CUDA_VISIBLE_DEVICES=1 python -u tasklauncher-20220905.py run --mode defense --defense_mode patchmixup --mix_mode maskmixup --sample_mode bernoullisampler --attack_mode autoattack --attack_eps 0.1 --blackbox --exp_name preactresnet50-svhn --cla_model preactresnet50 --cla_network_pkl /home/data/maggie/result-newhome/defense/patchmixup/fgsm/maskmixup-bernoullisampler/preactresnet50-svhn/blackbox/20220911/00004/patchmixup-svhn-dataset/patchmixup-trained-classifier-preactresnet50-on-svhn-epoch-0007-patch-cla2.pkl --dataset svhn --test_adv_dataset /home/data/maggie/result-newhome/attack/autoattack/preactresnet50-svhn/20220728/00000-autoattack-eps-0.1-acc-29.94/attack-svhn-dataset/samples/test --batch_size 256 --epochs 40 --lr 0.01 >> /home/maggie/mmat/log/SVHN/defense/patch-mixup-training/preactresnet50-svhn-patchmixup-autoattack-20220913.log 2>&1

# PreActResNet50 patchmixup beta(1,1) against deepfool (eps=0.1)
CUDA_VISIBLE_DEVICES=1 python -u tasklauncher-20220905.py run --mode defense --defense_mode patchmixup --mix_mode maskmixup --sample_mode bernoullisampler --attack_mode deepfool --attack_eps 0.1 --blackbox --exp_name preactresnet50-svhn --cla_model preactresnet50 --cla_network_pkl /home/data/maggie/result-newhome/defense/patchmixup/fgsm/maskmixup-bernoullisampler/preactresnet50-svhn/blackbox/20220911/00004/patchmixup-svhn-dataset/patchmixup-trained-classifier-preactresnet50-on-svhn-epoch-0007-patch-cla2.pkl --dataset svhn --test_adv_dataset /home/data/maggie/result-newhome/attack/deepfool/preactresnet50-svhn/20220721/00000-deepfool-eps-0.1-acc-23.72/attack-svhn-dataset/samples/test --batch_size 256 --epochs 40 --lr 0.01 >> /home/maggie/mmat/log/SVHN/defense/patch-mixup-training/preactresnet50-svhn-patchmixup-deepfool-20220913.log 2>&1

# PreActResNet50 patchmixup beta(1,1) against cw (eps=0.1)
CUDA_VISIBLE_DEVICES=1 python -u tasklauncher-20220905.py run --mode defense --defense_mode patchmixup --mix_mode maskmixup --sample_mode bernoullisampler --attack_mode cw --attack_eps 0.1 --blackbox --exp_name preactresnet50-svhn --cla_model preactresnet50 --cla_network_pkl /home/data/maggie/result-newhome/defense/patchmixup/fgsm/maskmixup-bernoullisampler/preactresnet50-svhn/blackbox/20220911/00004/patchmixup-svhn-dataset/patchmixup-trained-classifier-preactresnet50-on-svhn-epoch-0007-patch-cla2.pkl --dataset svhn --test_adv_dataset /home/data/maggie/result-newhome/attack/cw/preactresnet50-svhn/20220807/00000-cw-confidence-0.0-acc-27.09/attack-svhn-dataset/samples/test --batch_size 256 --epochs 40 --lr 0.01 >> /home/maggie/mmat/log/SVHN/defense/patch-mixup-training/preactresnet50-svhn-patchmixup-cw-20220913.log 2>&1

# PreActResNet50 patchmixup beta(1,1) against om-fgsm (eps=0.1)
CUDA_VISIBLE_DEVICES=1 python -u tasklauncher-20220905.py run --mode defense --defense_mode patchmixup --mix_mode maskmixup --sample_mode bernoullisampler --attack_mode om-fgsm --attack_eps 0.1 --blackbox --exp_name preactresnet50-svhn --cla_model preactresnet50 --cla_network_pkl /home/data/maggie/result-newhome/defense/patchmixup/fgsm/maskmixup-bernoullisampler/preactresnet50-svhn/blackbox/20220911/00004/patchmixup-svhn-dataset/patchmixup-trained-classifier-preactresnet50-on-svhn-epoch-0007-patch-cla2.pkl --dataset svhn --test_adv_dataset /home/data/maggie/result-newhome/attack/fgsm/preactresnet50-svhn/20220710/00002-omfgsm-eps-0.1-acc-40.01/attack-svhn-dataset/latent-attack-samples/test --batch_size 256 --epochs 40 --lr 0.01 >> /home/maggie/mmat/log/SVHN/defense/patch-mixup-training/preactresnet50-svhn-patchmixup-om-fgsm-20220913.log 2>&1

# PreActResNet50 patchmixup beta(1,1) against om-pgd (eps=0.1)
CUDA_VISIBLE_DEVICES=1 python -u tasklauncher-20220905.py run --mode defense --defense_mode patchmixup --mix_mode maskmixup --sample_mode bernoullisampler --attack_mode om-pgd --attack_eps 0.1 --blackbox --exp_name preactresnet50-svhn --cla_model preactresnet50 --cla_network_pkl /home/data/maggie/result-newhome/defense/patchmixup/fgsm/maskmixup-bernoullisampler/preactresnet50-svhn/blackbox/20220911/00004/patchmixup-svhn-dataset/patchmixup-trained-classifier-preactresnet50-on-svhn-epoch-0007-patch-cla2.pkl --dataset svhn --test_adv_dataset /home/data/maggie/result-newhome/attack/pgd/preactresnet50-svhn/20220713/00002-ompgd-eps-0.1-acc-6.73/attack-svhn-dataset/latent-attack-samples/test --batch_size 256 --epochs 40 --lr 0.01 >> /home/maggie/mmat/log/SVHN/defense/patch-mixup-training/preactresnet50-svhn-patchmixup-om-pgd-20220913.log 2>&1

# #   使用PGD对抗训练后的 cla3
# PreActResNet50 patchmixup beta(1,1) against pgd (eps=0.1)
CUDA_VISIBLE_DEVICES=1 python -u tasklauncher-20220905.py run --mode defense --defense_mode patchmixup --mix_mode maskmixup --sample_mode bernoullisampler --attack_mode pgd --attack_eps 0.1 --blackbox --exp_name preactresnet50-svhn --cla_model preactresnet50 --cla_network_pkl /home/data/maggie/result-newhome/defense/patchmixup/fgsm/maskmixup-bernoullisampler/preactresnet50-svhn/blackbox/20220912/00007/patchmixup-svhn-dataset/patchmixup-trained-classifier-preactresnet50-on-svhn-epoch-0014-patch-cla3.pkl --dataset svhn --test_adv_dataset /home/data/maggie/result-newhome/attack/pgd/preactresnet50-svhn/20220629/00002-pgd-eps-0.1-acc-35.61/attack-svhn-dataset/samples/test --batch_size 256 --epochs 40 --lr 0.01 >> /home/maggie/mmat/log/SVHN/defense/patch-mixup-training/preactresnet50-svhn-patchmixup-pgd-20220913.log 2>&1

# PreActResNet50 patchmixup beta(1,1) against autoattack (eps=0.1)
CUDA_VISIBLE_DEVICES=1 python -u tasklauncher-20220905.py run --mode defense --defense_mode patchmixup --mix_mode maskmixup --sample_mode bernoullisampler --attack_mode autoattack --attack_eps 0.1 --blackbox --exp_name preactresnet50-svhn --cla_model preactresnet50 --cla_network_pkl /home/data/maggie/result-newhome/defense/patchmixup/fgsm/maskmixup-bernoullisampler/preactresnet50-svhn/blackbox/20220912/00007/patchmixup-svhn-dataset/patchmixup-trained-classifier-preactresnet50-on-svhn-epoch-0014-patch-cla3.pkl --dataset svhn --test_adv_dataset /home/data/maggie/result-newhome/attack/autoattack/preactresnet50-svhn/20220728/00000-autoattack-eps-0.1-acc-29.94/attack-svhn-dataset/samples/test --batch_size 256 --epochs 40 --lr 0.01 >> /home/maggie/mmat/log/SVHN/defense/patch-mixup-training/preactresnet50-svhn-patchmixup-autoattack-20220913.log 2>&1

# PreActResNet50 patchmixup beta(1,1) against deepfool (eps=0.1)
CUDA_VISIBLE_DEVICES=1 python -u tasklauncher-20220905.py run --mode defense --defense_mode patchmixup --mix_mode maskmixup --sample_mode bernoullisampler --attack_mode deepfool --attack_eps 0.1 --blackbox --exp_name preactresnet50-svhn --cla_model preactresnet50 --cla_network_pkl /home/data/maggie/result-newhome/defense/patchmixup/fgsm/maskmixup-bernoullisampler/preactresnet50-svhn/blackbox/20220912/00007/patchmixup-svhn-dataset/patchmixup-trained-classifier-preactresnet50-on-svhn-epoch-0014-patch-cla3.pkl --dataset svhn --test_adv_dataset /home/data/maggie/result-newhome/attack/deepfool/preactresnet50-svhn/20220721/00000-deepfool-eps-0.1-acc-23.72/attack-svhn-dataset/samples/test --batch_size 256 --epochs 40 --lr 0.01 >> /home/maggie/mmat/log/SVHN/defense/patch-mixup-training/preactresnet50-svhn-patchmixup-deepfool-20220913.log 2>&1

# PreActResNet50 patchmixup beta(1,1) against cw (eps=0.1)
CUDA_VISIBLE_DEVICES=1 python -u tasklauncher-20220905.py run --mode defense --defense_mode patchmixup --mix_mode maskmixup --sample_mode bernoullisampler --attack_mode cw --attack_eps 0.1 --blackbox --exp_name preactresnet50-svhn --cla_model preactresnet50 --cla_network_pkl /home/data/maggie/result-newhome/defense/patchmixup/fgsm/maskmixup-bernoullisampler/preactresnet50-svhn/blackbox/20220912/00007/patchmixup-svhn-dataset/patchmixup-trained-classifier-preactresnet50-on-svhn-epoch-0014-patch-cla3.pkl --dataset svhn --test_adv_dataset /home/data/maggie/result-newhome/attack/cw/preactresnet50-svhn/20220807/00000-cw-confidence-0.0-acc-27.09/attack-svhn-dataset/samples/test --batch_size 256 --epochs 40 --lr 0.01 >> /home/maggie/mmat/log/SVHN/defense/patch-mixup-training/preactresnet50-svhn-patchmixup-cw-20220913.log 2>&1

# PreActResNet50 patchmixup beta(1,1) against om-fgsm (eps=0.1)
CUDA_VISIBLE_DEVICES=1 python -u tasklauncher-20220905.py run --mode defense --defense_mode patchmixup --mix_mode maskmixup --sample_mode bernoullisampler --attack_mode om-fgsm --attack_eps 0.1 --blackbox --exp_name preactresnet50-svhn --cla_model preactresnet50 --cla_network_pkl /home/data/maggie/result-newhome/defense/patchmixup/fgsm/maskmixup-bernoullisampler/preactresnet50-svhn/blackbox/20220912/00007/patchmixup-svhn-dataset/patchmixup-trained-classifier-preactresnet50-on-svhn-epoch-0014-patch-cla3.pkl --dataset svhn --test_adv_dataset /home/data/maggie/result-newhome/attack/fgsm/preactresnet50-svhn/20220710/00002-omfgsm-eps-0.1-acc-40.01/attack-svhn-dataset/latent-attack-samples/test --batch_size 256 --epochs 40 --lr 0.01 >> /home/maggie/mmat/log/SVHN/defense/patch-mixup-training/preactresnet50-svhn-patchmixup-om-fgsm-20220913.log 2>&1

# PreActResNet50 patchmixup beta(1,1) against om-pgd (eps=0.1)
CUDA_VISIBLE_DEVICES=1 python -u tasklauncher-20220905.py run --mode defense --defense_mode patchmixup --mix_mode maskmixup --sample_mode bernoullisampler --attack_mode om-pgd --attack_eps 0.1 --blackbox --exp_name preactresnet50-svhn --cla_model preactresnet50 --cla_network_pkl /home/data/maggie/result-newhome/defense/patchmixup/fgsm/maskmixup-bernoullisampler/preactresnet50-svhn/blackbox/20220912/00007/patchmixup-svhn-dataset/patchmixup-trained-classifier-preactresnet50-on-svhn-epoch-0014-patch-cla3.pkl --dataset svhn --test_adv_dataset /home/data/maggie/result-newhome/attack/pgd/preactresnet50-svhn/20220713/00002-ompgd-eps-0.1-acc-6.73/attack-svhn-dataset/latent-attack-samples/test --batch_size 256 --epochs 40 --lr 0.01 >> /home/maggie/mmat/log/SVHN/defense/patch-mixup-training/preactresnet50-svhn-patchmixup-om-pgd-20220913.log 2>&1

# #   使用PGD对抗训练后的 cla4
# PreActResNet50 patchmixup beta(1,1) against pgd (eps=0.1)
CUDA_VISIBLE_DEVICES=1 python -u tasklauncher-20220905.py run --mode defense --defense_mode patchmixup --mix_mode maskmixup --sample_mode bernoullisampler --attack_mode pgd --attack_eps 0.1 --blackbox --exp_name preactresnet50-svhn --cla_model preactresnet50 --cla_network_pkl /home/data/maggie/result-newhome/defense/patchmixup/fgsm/maskmixup-bernoullisampler/preactresnet50-svhn/blackbox/20220913/00002/patchmixup-svhn-dataset/patchmixup-trained-classifier-preactresnet50-on-svhn-epoch-0005-patch-cla4.pkl --dataset svhn --test_adv_dataset /home/data/maggie/result-newhome/attack/pgd/preactresnet50-svhn/20220629/00002-pgd-eps-0.1-acc-35.61/attack-svhn-dataset/samples/test --batch_size 256 --epochs 40 --lr 0.01 >> /home/maggie/mmat/log/SVHN/defense/patch-mixup-training/preactresnet50-svhn-patchmixup-pgd-20220913.log 2>&1

# PreActResNet50 patchmixup beta(1,1) against autoattack (eps=0.1)
CUDA_VISIBLE_DEVICES=1 python -u tasklauncher-20220905.py run --mode defense --defense_mode patchmixup --mix_mode maskmixup --sample_mode bernoullisampler --attack_mode autoattack --attack_eps 0.1 --blackbox --exp_name preactresnet50-svhn --cla_model preactresnet50 --cla_network_pkl /home/data/maggie/result-newhome/defense/patchmixup/fgsm/maskmixup-bernoullisampler/preactresnet50-svhn/blackbox/20220913/00002/patchmixup-svhn-dataset/patchmixup-trained-classifier-preactresnet50-on-svhn-epoch-0005-patch-cla4.pkl --dataset svhn --test_adv_dataset /home/data/maggie/result-newhome/attack/autoattack/preactresnet50-svhn/20220728/00000-autoattack-eps-0.1-acc-29.94/attack-svhn-dataset/samples/test --batch_size 256 --epochs 40 --lr 0.01 >> /home/maggie/mmat/log/SVHN/defense/patch-mixup-training/preactresnet50-svhn-patchmixup-autoattack-20220913.log 2>&1

# PreActResNet50 patchmixup beta(1,1) against deepfool (eps=0.1)
CUDA_VISIBLE_DEVICES=1 python -u tasklauncher-20220905.py run --mode defense --defense_mode patchmixup --mix_mode maskmixup --sample_mode bernoullisampler --attack_mode deepfool --attack_eps 0.1 --blackbox --exp_name preactresnet50-svhn --cla_model preactresnet50 --cla_network_pkl /home/data/maggie/result-newhome/defense/patchmixup/fgsm/maskmixup-bernoullisampler/preactresnet50-svhn/blackbox/20220913/00002/patchmixup-svhn-dataset/patchmixup-trained-classifier-preactresnet50-on-svhn-epoch-0005-patch-cla4.pkl --dataset svhn --test_adv_dataset /home/data/maggie/result-newhome/attack/deepfool/preactresnet50-svhn/20220721/00000-deepfool-eps-0.1-acc-23.72/attack-svhn-dataset/samples/test --batch_size 256 --epochs 40 --lr 0.01 >> /home/maggie/mmat/log/SVHN/defense/patch-mixup-training/preactresnet50-svhn-patchmixup-deepfool-20220913.log 2>&1

# PreActResNet50 patchmixup beta(1,1) against cw (eps=0.1)
CUDA_VISIBLE_DEVICES=1 python -u tasklauncher-20220905.py run --mode defense --defense_mode patchmixup --mix_mode maskmixup --sample_mode bernoullisampler --attack_mode cw --attack_eps 0.1 --blackbox --exp_name preactresnet50-svhn --cla_model preactresnet50 --cla_network_pkl /home/data/maggie/result-newhome/defense/patchmixup/fgsm/maskmixup-bernoullisampler/preactresnet50-svhn/blackbox/20220913/00002/patchmixup-svhn-dataset/patchmixup-trained-classifier-preactresnet50-on-svhn-epoch-0005-patch-cla4.pkl --dataset svhn --test_adv_dataset /home/data/maggie/result-newhome/attack/cw/preactresnet50-svhn/20220807/00000-cw-confidence-0.0-acc-27.09/attack-svhn-dataset/samples/test --batch_size 256 --epochs 40 --lr 0.01 >> /home/maggie/mmat/log/SVHN/defense/patch-mixup-training/preactresnet50-svhn-patchmixup-cw-20220913.log 2>&1

# PreActResNet50 patchmixup beta(1,1) against om-fgsm (eps=0.1)
CUDA_VISIBLE_DEVICES=1 python -u tasklauncher-20220905.py run --mode defense --defense_mode patchmixup --mix_mode maskmixup --sample_mode bernoullisampler --attack_mode om-fgsm --attack_eps 0.1 --blackbox --exp_name preactresnet50-svhn --cla_model preactresnet50 --cla_network_pkl /home/data/maggie/result-newhome/defense/patchmixup/fgsm/maskmixup-bernoullisampler/preactresnet50-svhn/blackbox/20220913/00002/patchmixup-svhn-dataset/patchmixup-trained-classifier-preactresnet50-on-svhn-epoch-0005-patch-cla4.pkl --dataset svhn --test_adv_dataset /home/data/maggie/result-newhome/attack/fgsm/preactresnet50-svhn/20220710/00002-omfgsm-eps-0.1-acc-40.01/attack-svhn-dataset/latent-attack-samples/test --batch_size 256 --epochs 40 --lr 0.01 >> /home/maggie/mmat/log/SVHN/defense/patch-mixup-training/preactresnet50-svhn-patchmixup-om-fgsm-20220913.log 2>&1

# PreActResNet50 patchmixup beta(1,1) against om-pgd (eps=0.1)
CUDA_VISIBLE_DEVICES=1 python -u tasklauncher-20220905.py run --mode defense --defense_mode patchmixup --mix_mode maskmixup --sample_mode bernoullisampler --attack_mode om-pgd --attack_eps 0.1 --blackbox --exp_name preactresnet50-svhn --cla_model preactresnet50 --cla_network_pkl /home/data/maggie/result-newhome/defense/patchmixup/fgsm/maskmixup-bernoullisampler/preactresnet50-svhn/blackbox/20220913/00002/patchmixup-svhn-dataset/patchmixup-trained-classifier-preactresnet50-on-svhn-epoch-0005-patch-cla4.pkl --dataset svhn --test_adv_dataset /home/data/maggie/result-newhome/attack/pgd/preactresnet50-svhn/20220713/00002-ompgd-eps-0.1-acc-6.73/attack-svhn-dataset/latent-attack-samples/test --batch_size 256 --epochs 40 --lr 0.01 >> /home/maggie/mmat/log/SVHN/defense/patch-mixup-training/preactresnet50-svhn-patchmixup-om-pgd-20220913.log 2>&1

# #   使用PGD对抗训练后的 cla5
# PreActResNet50 patchmixup beta(1,1) against pgd (eps=0.1)
CUDA_VISIBLE_DEVICES=1 python -u tasklauncher-20220905.py run --mode defense --defense_mode patchmixup --mix_mode maskmixup --sample_mode bernoullisampler --attack_mode pgd --attack_eps 0.1 --blackbox --exp_name preactresnet50-svhn --cla_model preactresnet50 --cla_network_pkl /home/data/maggie/result-newhome/defense/patchmixup/fgsm/maskmixup-bernoullisampler/preactresnet50-svhn/blackbox/20220913/00002/patchmixup-svhn-dataset/patchmixup-trained-classifier-preactresnet50-on-svhn-epoch-0006-patch-cla5.pkl --dataset svhn --test_adv_dataset /home/data/maggie/result-newhome/attack/pgd/preactresnet50-svhn/20220629/00002-pgd-eps-0.1-acc-35.61/attack-svhn-dataset/samples/test --batch_size 256 --epochs 40 --lr 0.01 >> /home/maggie/mmat/log/SVHN/defense/patch-mixup-training/preactresnet50-svhn-patchmixup-pgd-20220913.log 2>&1

# PreActResNet50 patchmixup beta(1,1) against autoattack (eps=0.1)
CUDA_VISIBLE_DEVICES=1 python -u tasklauncher-20220905.py run --mode defense --defense_mode patchmixup --mix_mode maskmixup --sample_mode bernoullisampler --attack_mode autoattack --attack_eps 0.1 --blackbox --exp_name preactresnet50-svhn --cla_model preactresnet50 --cla_network_pkl /home/data/maggie/result-newhome/defense/patchmixup/fgsm/maskmixup-bernoullisampler/preactresnet50-svhn/blackbox/20220913/00002/patchmixup-svhn-dataset/patchmixup-trained-classifier-preactresnet50-on-svhn-epoch-0006-patch-cla5.pkl --dataset svhn --test_adv_dataset /home/data/maggie/result-newhome/attack/autoattack/preactresnet50-svhn/20220728/00000-autoattack-eps-0.1-acc-29.94/attack-svhn-dataset/samples/test --batch_size 256 --epochs 40 --lr 0.01 >> /home/maggie/mmat/log/SVHN/defense/patch-mixup-training/preactresnet50-svhn-patchmixup-autoattack-20220913.log 2>&1

# PreActResNet50 patchmixup beta(1,1) against deepfool (eps=0.1)
CUDA_VISIBLE_DEVICES=1 python -u tasklauncher-20220905.py run --mode defense --defense_mode patchmixup --mix_mode maskmixup --sample_mode bernoullisampler --attack_mode deepfool --attack_eps 0.1 --blackbox --exp_name preactresnet50-svhn --cla_model preactresnet50 --cla_network_pkl /home/data/maggie/result-newhome/defense/patchmixup/fgsm/maskmixup-bernoullisampler/preactresnet50-svhn/blackbox/20220913/00002/patchmixup-svhn-dataset/patchmixup-trained-classifier-preactresnet50-on-svhn-epoch-0006-patch-cla5.pkl --dataset svhn --test_adv_dataset /home/data/maggie/result-newhome/attack/deepfool/preactresnet50-svhn/20220721/00000-deepfool-eps-0.1-acc-23.72/attack-svhn-dataset/samples/test --batch_size 256 --epochs 40 --lr 0.01 >> /home/maggie/mmat/log/SVHN/defense/patch-mixup-training/preactresnet50-svhn-patchmixup-deepfool-20220913.log 2>&1

# PreActResNet50 patchmixup beta(1,1) against cw (eps=0.1)
CUDA_VISIBLE_DEVICES=1 python -u tasklauncher-20220905.py run --mode defense --defense_mode patchmixup --mix_mode maskmixup --sample_mode bernoullisampler --attack_mode cw --attack_eps 0.1 --blackbox --exp_name preactresnet50-svhn --cla_model preactresnet50 --cla_network_pkl /home/data/maggie/result-newhome/defense/patchmixup/fgsm/maskmixup-bernoullisampler/preactresnet50-svhn/blackbox/20220913/00002/patchmixup-svhn-dataset/patchmixup-trained-classifier-preactresnet50-on-svhn-epoch-0006-patch-cla5.pkl --dataset svhn --test_adv_dataset /home/data/maggie/result-newhome/attack/cw/preactresnet50-svhn/20220807/00000-cw-confidence-0.0-acc-27.09/attack-svhn-dataset/samples/test --batch_size 256 --epochs 40 --lr 0.01 >> /home/maggie/mmat/log/SVHN/defense/patch-mixup-training/preactresnet50-svhn-patchmixup-cw-20220913.log 2>&1

# PreActResNet50 patchmixup beta(1,1) against om-fgsm (eps=0.1)
CUDA_VISIBLE_DEVICES=1 python -u tasklauncher-20220905.py run --mode defense --defense_mode patchmixup --mix_mode maskmixup --sample_mode bernoullisampler --attack_mode om-fgsm --attack_eps 0.1 --blackbox --exp_name preactresnet50-svhn --cla_model preactresnet50 --cla_network_pkl /home/data/maggie/result-newhome/defense/patchmixup/fgsm/maskmixup-bernoullisampler/preactresnet50-svhn/blackbox/20220913/00002/patchmixup-svhn-dataset/patchmixup-trained-classifier-preactresnet50-on-svhn-epoch-0006-patch-cla5.pkl --dataset svhn --test_adv_dataset /home/data/maggie/result-newhome/attack/fgsm/preactresnet50-svhn/20220710/00002-omfgsm-eps-0.1-acc-40.01/attack-svhn-dataset/latent-attack-samples/test --batch_size 256 --epochs 40 --lr 0.01 >> /home/maggie/mmat/log/SVHN/defense/patch-mixup-training/preactresnet50-svhn-patchmixup-om-fgsm-20220913.log 2>&1

# PreActResNet50 patchmixup beta(1,1) against om-pgd (eps=0.1)
CUDA_VISIBLE_DEVICES=1 python -u tasklauncher-20220905.py run --mode defense --defense_mode patchmixup --mix_mode maskmixup --sample_mode bernoullisampler --attack_mode om-pgd --attack_eps 0.1 --blackbox --exp_name preactresnet50-svhn --cla_model preactresnet50 --cla_network_pkl /home/data/maggie/result-newhome/defense/patchmixup/fgsm/maskmixup-bernoullisampler/preactresnet50-svhn/blackbox/20220913/00002/patchmixup-svhn-dataset/patchmixup-trained-classifier-preactresnet50-on-svhn-epoch-0006-patch-cla5.pkl --dataset svhn --test_adv_dataset /home/data/maggie/result-newhome/attack/pgd/preactresnet50-svhn/20220713/00002-ompgd-eps-0.1-acc-6.73/attack-svhn-dataset/latent-attack-samples/test --batch_size 256 --epochs 40 --lr 0.01 >> /home/maggie/mmat/log/SVHN/defense/patch-mixup-training/preactresnet50-svhn-patchmixup-om-pgd-20220913.log 2>&1

# #   使用PGD对抗训练后的 cla6
# PreActResNet50 patchmixup beta(1,1) against pgd (eps=0.1)
CUDA_VISIBLE_DEVICES=1 python -u tasklauncher-20220905.py run --mode defense --defense_mode patchmixup --mix_mode maskmixup --sample_mode bernoullisampler --attack_mode pgd --attack_eps 0.1 --blackbox --exp_name preactresnet50-svhn --cla_model preactresnet50 --cla_network_pkl /home/data/maggie/result-newhome/defense/patchmixup/fgsm/maskmixup-bernoullisampler/preactresnet50-svhn/blackbox/20220913/00002/patchmixup-svhn-dataset/patchmixup-trained-classifier-preactresnet50-on-svhn-epoch-0007-patch-cla6.pkl --dataset svhn --test_adv_dataset /home/data/maggie/result-newhome/attack/pgd/preactresnet50-svhn/20220629/00002-pgd-eps-0.1-acc-35.61/attack-svhn-dataset/samples/test --batch_size 256 --epochs 40 --lr 0.01 >> /home/maggie/mmat/log/SVHN/defense/patch-mixup-training/preactresnet50-svhn-patchmixup-pgd-20220913.log 2>&1

# PreActResNet50 patchmixup beta(1,1) against autoattack (eps=0.1)
CUDA_VISIBLE_DEVICES=1 python -u tasklauncher-20220905.py run --mode defense --defense_mode patchmixup --mix_mode maskmixup --sample_mode bernoullisampler --attack_mode autoattack --attack_eps 0.1 --blackbox --exp_name preactresnet50-svhn --cla_model preactresnet50 --cla_network_pkl /home/data/maggie/result-newhome/defense/patchmixup/fgsm/maskmixup-bernoullisampler/preactresnet50-svhn/blackbox/20220913/00002/patchmixup-svhn-dataset/patchmixup-trained-classifier-preactresnet50-on-svhn-epoch-0007-patch-cla6.pkl --dataset svhn --test_adv_dataset /home/data/maggie/result-newhome/attack/autoattack/preactresnet50-svhn/20220728/00000-autoattack-eps-0.1-acc-29.94/attack-svhn-dataset/samples/test --batch_size 256 --epochs 40 --lr 0.01 >> /home/maggie/mmat/log/SVHN/defense/patch-mixup-training/preactresnet50-svhn-patchmixup-autoattack-20220913.log 2>&1

# PreActResNet50 patchmixup beta(1,1) against deepfool (eps=0.1)
CUDA_VISIBLE_DEVICES=1 python -u tasklauncher-20220905.py run --mode defense --defense_mode patchmixup --mix_mode maskmixup --sample_mode bernoullisampler --attack_mode deepfool --attack_eps 0.1 --blackbox --exp_name preactresnet50-svhn --cla_model preactresnet50 --cla_network_pkl /home/data/maggie/result-newhome/defense/patchmixup/fgsm/maskmixup-bernoullisampler/preactresnet50-svhn/blackbox/20220913/00002/patchmixup-svhn-dataset/patchmixup-trained-classifier-preactresnet50-on-svhn-epoch-0007-patch-cla6.pkl --dataset svhn --test_adv_dataset /home/data/maggie/result-newhome/attack/deepfool/preactresnet50-svhn/20220721/00000-deepfool-eps-0.1-acc-23.72/attack-svhn-dataset/samples/test --batch_size 256 --epochs 40 --lr 0.01 >> /home/maggie/mmat/log/SVHN/defense/patch-mixup-training/preactresnet50-svhn-patchmixup-deepfool-20220913.log 2>&1

# PreActResNet50 patchmixup beta(1,1) against cw (eps=0.1)
CUDA_VISIBLE_DEVICES=1 python -u tasklauncher-20220905.py run --mode defense --defense_mode patchmixup --mix_mode maskmixup --sample_mode bernoullisampler --attack_mode cw --attack_eps 0.1 --blackbox --exp_name preactresnet50-svhn --cla_model preactresnet50 --cla_network_pkl /home/data/maggie/result-newhome/defense/patchmixup/fgsm/maskmixup-bernoullisampler/preactresnet50-svhn/blackbox/20220913/00002/patchmixup-svhn-dataset/patchmixup-trained-classifier-preactresnet50-on-svhn-epoch-0007-patch-cla6.pkl --dataset svhn --test_adv_dataset /home/data/maggie/result-newhome/attack/cw/preactresnet50-svhn/20220807/00000-cw-confidence-0.0-acc-27.09/attack-svhn-dataset/samples/test --batch_size 256 --epochs 40 --lr 0.01 >> /home/maggie/mmat/log/SVHN/defense/patch-mixup-training/preactresnet50-svhn-patchmixup-cw-20220913.log 2>&1

# PreActResNet50 patchmixup beta(1,1) against om-fgsm (eps=0.1)
CUDA_VISIBLE_DEVICES=1 python -u tasklauncher-20220905.py run --mode defense --defense_mode patchmixup --mix_mode maskmixup --sample_mode bernoullisampler --attack_mode om-fgsm --attack_eps 0.1 --blackbox --exp_name preactresnet50-svhn --cla_model preactresnet50 --cla_network_pkl /home/data/maggie/result-newhome/defense/patchmixup/fgsm/maskmixup-bernoullisampler/preactresnet50-svhn/blackbox/20220913/00002/patchmixup-svhn-dataset/patchmixup-trained-classifier-preactresnet50-on-svhn-epoch-0007-patch-cla6.pkl --dataset svhn --test_adv_dataset /home/data/maggie/result-newhome/attack/fgsm/preactresnet50-svhn/20220710/00002-omfgsm-eps-0.1-acc-40.01/attack-svhn-dataset/latent-attack-samples/test --batch_size 256 --epochs 40 --lr 0.01 >> /home/maggie/mmat/log/SVHN/defense/patch-mixup-training/preactresnet50-svhn-patchmixup-om-fgsm-20220913.log 2>&1

# PreActResNet50 patchmixup beta(1,1) against om-pgd (eps=0.1)
CUDA_VISIBLE_DEVICES=1 python -u tasklauncher-20220905.py run --mode defense --defense_mode patchmixup --mix_mode maskmixup --sample_mode bernoullisampler --attack_mode om-pgd --attack_eps 0.1 --blackbox --exp_name preactresnet50-svhn --cla_model preactresnet50 --cla_network_pkl /home/data/maggie/result-newhome/defense/patchmixup/fgsm/maskmixup-bernoullisampler/preactresnet50-svhn/blackbox/20220913/00002/patchmixup-svhn-dataset/patchmixup-trained-classifier-preactresnet50-on-svhn-epoch-0007-patch-cla6.pkl --dataset svhn --test_adv_dataset /home/data/maggie/result-newhome/attack/pgd/preactresnet50-svhn/20220713/00002-ompgd-eps-0.1-acc-6.73/attack-svhn-dataset/latent-attack-samples/test --batch_size 256 --epochs 40 --lr 0.01 >> /home/maggie/mmat/log/SVHN/defense/patch-mixup-training/preactresnet50-svhn-patchmixup-om-pgd-20220913.log 2>&1


# #   使用PGD对抗训练后的 cla7
# PreActResNet50 patchmixup beta(1,1) against pgd (eps=0.1)
CUDA_VISIBLE_DEVICES=1 python -u tasklauncher-20220905.py run --mode defense --defense_mode patchmixup --mix_mode maskmixup --sample_mode bernoullisampler --attack_mode pgd --attack_eps 0.1 --blackbox --exp_name preactresnet50-svhn --cla_model preactresnet50 --cla_network_pkl /home/data/maggie/result-newhome/defense/patchmixup/fgsm/maskmixup-bernoullisampler/preactresnet50-svhn/blackbox/20220913/00004/patchmixup-svhn-dataset/patchmixup-trained-classifier-preactresnet50-on-svhn-epoch-0005-patch-cla7.pkl --dataset svhn --test_adv_dataset /home/data/maggie/result-newhome/attack/pgd/preactresnet50-svhn/20220629/00002-pgd-eps-0.1-acc-35.61/attack-svhn-dataset/samples/test --batch_size 256 --epochs 40 --lr 0.01 >> /home/maggie/mmat/log/SVHN/defense/patch-mixup-training/preactresnet50-svhn-patchmixup-pgd-20220913.log 2>&1

# PreActResNet50 patchmixup beta(1,1) against autoattack (eps=0.1)
CUDA_VISIBLE_DEVICES=1 python -u tasklauncher-20220905.py run --mode defense --defense_mode patchmixup --mix_mode maskmixup --sample_mode bernoullisampler --attack_mode autoattack --attack_eps 0.1 --blackbox --exp_name preactresnet50-svhn --cla_model preactresnet50 --cla_network_pkl /home/data/maggie/result-newhome/defense/patchmixup/fgsm/maskmixup-bernoullisampler/preactresnet50-svhn/blackbox/20220913/00004/patchmixup-svhn-dataset/patchmixup-trained-classifier-preactresnet50-on-svhn-epoch-0005-patch-cla7.pkl --dataset svhn --test_adv_dataset /home/data/maggie/result-newhome/attack/autoattack/preactresnet50-svhn/20220728/00000-autoattack-eps-0.1-acc-29.94/attack-svhn-dataset/samples/test --batch_size 256 --epochs 40 --lr 0.01 >> /home/maggie/mmat/log/SVHN/defense/patch-mixup-training/preactresnet50-svhn-patchmixup-autoattack-20220913.log 2>&1

# PreActResNet50 patchmixup beta(1,1) against deepfool (eps=0.1)
CUDA_VISIBLE_DEVICES=1 python -u tasklauncher-20220905.py run --mode defense --defense_mode patchmixup --mix_mode maskmixup --sample_mode bernoullisampler --attack_mode deepfool --attack_eps 0.1 --blackbox --exp_name preactresnet50-svhn --cla_model preactresnet50 --cla_network_pkl /home/data/maggie/result-newhome/defense/patchmixup/fgsm/maskmixup-bernoullisampler/preactresnet50-svhn/blackbox/20220913/00004/patchmixup-svhn-dataset/patchmixup-trained-classifier-preactresnet50-on-svhn-epoch-0005-patch-cla7.pkl --dataset svhn --test_adv_dataset /home/data/maggie/result-newhome/attack/deepfool/preactresnet50-svhn/20220721/00000-deepfool-eps-0.1-acc-23.72/attack-svhn-dataset/samples/test --batch_size 256 --epochs 40 --lr 0.01 >> /home/maggie/mmat/log/SVHN/defense/patch-mixup-training/preactresnet50-svhn-patchmixup-deepfool-20220913.log 2>&1

# PreActResNet50 patchmixup beta(1,1) against cw (eps=0.1)
CUDA_VISIBLE_DEVICES=1 python -u tasklauncher-20220905.py run --mode defense --defense_mode patchmixup --mix_mode maskmixup --sample_mode bernoullisampler --attack_mode cw --attack_eps 0.1 --blackbox --exp_name preactresnet50-svhn --cla_model preactresnet50 --cla_network_pkl /home/data/maggie/result-newhome/defense/patchmixup/fgsm/maskmixup-bernoullisampler/preactresnet50-svhn/blackbox/20220913/00004/patchmixup-svhn-dataset/patchmixup-trained-classifier-preactresnet50-on-svhn-epoch-0005-patch-cla7.pkl --dataset svhn --test_adv_dataset /home/data/maggie/result-newhome/attack/cw/preactresnet50-svhn/20220807/00000-cw-confidence-0.0-acc-27.09/attack-svhn-dataset/samples/test --batch_size 256 --epochs 40 --lr 0.01 >> /home/maggie/mmat/log/SVHN/defense/patch-mixup-training/preactresnet50-svhn-patchmixup-cw-20220913.log 2>&1

# PreActResNet50 patchmixup beta(1,1) against om-fgsm (eps=0.1)
CUDA_VISIBLE_DEVICES=1 python -u tasklauncher-20220905.py run --mode defense --defense_mode patchmixup --mix_mode maskmixup --sample_mode bernoullisampler --attack_mode om-fgsm --attack_eps 0.1 --blackbox --exp_name preactresnet50-svhn --cla_model preactresnet50 --cla_network_pkl /home/data/maggie/result-newhome/defense/patchmixup/fgsm/maskmixup-bernoullisampler/preactresnet50-svhn/blackbox/20220913/00004/patchmixup-svhn-dataset/patchmixup-trained-classifier-preactresnet50-on-svhn-epoch-0005-patch-cla7.pkl --dataset svhn --test_adv_dataset /home/data/maggie/result-newhome/attack/fgsm/preactresnet50-svhn/20220710/00002-omfgsm-eps-0.1-acc-40.01/attack-svhn-dataset/latent-attack-samples/test --batch_size 256 --epochs 40 --lr 0.01 >> /home/maggie/mmat/log/SVHN/defense/patch-mixup-training/preactresnet50-svhn-patchmixup-om-fgsm-20220913.log 2>&1

# PreActResNet50 patchmixup beta(1,1) against om-pgd (eps=0.1)
CUDA_VISIBLE_DEVICES=1 python -u tasklauncher-20220905.py run --mode defense --defense_mode patchmixup --mix_mode maskmixup --sample_mode bernoullisampler --attack_mode om-pgd --attack_eps 0.1 --blackbox --exp_name preactresnet50-svhn --cla_model preactresnet50 --cla_network_pkl /home/data/maggie/result-newhome/defense/patchmixup/fgsm/maskmixup-bernoullisampler/preactresnet50-svhn/blackbox/20220913/00004/patchmixup-svhn-dataset/patchmixup-trained-classifier-preactresnet50-on-svhn-epoch-0005-patch-cla7.pkl --dataset svhn --test_adv_dataset /home/data/maggie/result-newhome/attack/pgd/preactresnet50-svhn/20220713/00002-ompgd-eps-0.1-acc-6.73/attack-svhn-dataset/latent-attack-samples/test --batch_size 256 --epochs 40 --lr 0.01 >> /home/maggie/mmat/log/SVHN/defense/patch-mixup-training/preactresnet50-svhn-patchmixup-om-pgd-20220913.log 2>&1



# #   使用PGD对抗训练后的 cla8
# PreActResNet50 patchmixup beta(1,1) against pgd (eps=0.1)
CUDA_VISIBLE_DEVICES=1 python -u tasklauncher-20220905.py run --mode defense --defense_mode patchmixup --mix_mode maskmixup --sample_mode bernoullisampler --attack_mode pgd --attack_eps 0.1 --blackbox --exp_name preactresnet50-svhn --cla_model preactresnet50 --cla_network_pkl /home/data/maggie/result-newhome/defense/patchmixup/fgsm/maskmixup-bernoullisampler/preactresnet50-svhn/blackbox/20220913/00004/patchmixup-svhn-dataset/patchmixup-trained-classifier-preactresnet50-on-svhn-epoch-0006-patch-cla8.pkl --dataset svhn --test_adv_dataset /home/data/maggie/result-newhome/attack/pgd/preactresnet50-svhn/20220629/00002-pgd-eps-0.1-acc-35.61/attack-svhn-dataset/samples/test --batch_size 256 --epochs 40 --lr 0.01 >> /home/maggie/mmat/log/SVHN/defense/patch-mixup-training/preactresnet50-svhn-patchmixup-pgd-20220913.log 2>&1

# PreActResNet50 patchmixup beta(1,1) against autoattack (eps=0.1)
CUDA_VISIBLE_DEVICES=1 python -u tasklauncher-20220905.py run --mode defense --defense_mode patchmixup --mix_mode maskmixup --sample_mode bernoullisampler --attack_mode autoattack --attack_eps 0.1 --blackbox --exp_name preactresnet50-svhn --cla_model preactresnet50 --cla_network_pkl /home/data/maggie/result-newhome/defense/patchmixup/fgsm/maskmixup-bernoullisampler/preactresnet50-svhn/blackbox/20220913/00004/patchmixup-svhn-dataset/patchmixup-trained-classifier-preactresnet50-on-svhn-epoch-0006-patch-cla8.pkl --dataset svhn --test_adv_dataset /home/data/maggie/result-newhome/attack/autoattack/preactresnet50-svhn/20220728/00000-autoattack-eps-0.1-acc-29.94/attack-svhn-dataset/samples/test --batch_size 256 --epochs 40 --lr 0.01 >> /home/maggie/mmat/log/SVHN/defense/patch-mixup-training/preactresnet50-svhn-patchmixup-autoattack-20220913.log 2>&1

# PreActResNet50 patchmixup beta(1,1) against deepfool (eps=0.1)
CUDA_VISIBLE_DEVICES=1 python -u tasklauncher-20220905.py run --mode defense --defense_mode patchmixup --mix_mode maskmixup --sample_mode bernoullisampler --attack_mode deepfool --attack_eps 0.1 --blackbox --exp_name preactresnet50-svhn --cla_model preactresnet50 --cla_network_pkl /home/data/maggie/result-newhome/defense/patchmixup/fgsm/maskmixup-bernoullisampler/preactresnet50-svhn/blackbox/20220913/00004/patchmixup-svhn-dataset/patchmixup-trained-classifier-preactresnet50-on-svhn-epoch-0006-patch-cla8.pkl --dataset svhn --test_adv_dataset /home/data/maggie/result-newhome/attack/deepfool/preactresnet50-svhn/20220721/00000-deepfool-eps-0.1-acc-23.72/attack-svhn-dataset/samples/test --batch_size 256 --epochs 40 --lr 0.01 >> /home/maggie/mmat/log/SVHN/defense/patch-mixup-training/preactresnet50-svhn-patchmixup-deepfool-20220913.log 2>&1

# PreActResNet50 patchmixup beta(1,1) against cw (eps=0.1)
CUDA_VISIBLE_DEVICES=1 python -u tasklauncher-20220905.py run --mode defense --defense_mode patchmixup --mix_mode maskmixup --sample_mode bernoullisampler --attack_mode cw --attack_eps 0.1 --blackbox --exp_name preactresnet50-svhn --cla_model preactresnet50 --cla_network_pkl /home/data/maggie/result-newhome/defense/patchmixup/fgsm/maskmixup-bernoullisampler/preactresnet50-svhn/blackbox/20220913/00004/patchmixup-svhn-dataset/patchmixup-trained-classifier-preactresnet50-on-svhn-epoch-0006-patch-cla8.pkl --dataset svhn --test_adv_dataset /home/data/maggie/result-newhome/attack/cw/preactresnet50-svhn/20220807/00000-cw-confidence-0.0-acc-27.09/attack-svhn-dataset/samples/test --batch_size 256 --epochs 40 --lr 0.01 >> /home/maggie/mmat/log/SVHN/defense/patch-mixup-training/preactresnet50-svhn-patchmixup-cw-20220913.log 2>&1

# PreActResNet50 patchmixup beta(1,1) against om-fgsm (eps=0.1)
CUDA_VISIBLE_DEVICES=1 python -u tasklauncher-20220905.py run --mode defense --defense_mode patchmixup --mix_mode maskmixup --sample_mode bernoullisampler --attack_mode om-fgsm --attack_eps 0.1 --blackbox --exp_name preactresnet50-svhn --cla_model preactresnet50 --cla_network_pkl /home/data/maggie/result-newhome/defense/patchmixup/fgsm/maskmixup-bernoullisampler/preactresnet50-svhn/blackbox/20220913/00004/patchmixup-svhn-dataset/patchmixup-trained-classifier-preactresnet50-on-svhn-epoch-0006-patch-cla8.pkl --dataset svhn --test_adv_dataset /home/data/maggie/result-newhome/attack/fgsm/preactresnet50-svhn/20220710/00002-omfgsm-eps-0.1-acc-40.01/attack-svhn-dataset/latent-attack-samples/test --batch_size 256 --epochs 40 --lr 0.01 >> /home/maggie/mmat/log/SVHN/defense/patch-mixup-training/preactresnet50-svhn-patchmixup-om-fgsm-20220913.log 2>&1

# PreActResNet50 patchmixup beta(1,1) against om-pgd (eps=0.1)
CUDA_VISIBLE_DEVICES=1 python -u tasklauncher-20220905.py run --mode defense --defense_mode patchmixup --mix_mode maskmixup --sample_mode bernoullisampler --attack_mode om-pgd --attack_eps 0.1 --blackbox --exp_name preactresnet50-svhn --cla_model preactresnet50 --cla_network_pkl /home/data/maggie/result-newhome/defense/patchmixup/fgsm/maskmixup-bernoullisampler/preactresnet50-svhn/blackbox/20220913/00004/patchmixup-svhn-dataset/patchmixup-trained-classifier-preactresnet50-on-svhn-epoch-0006-patch-cla8.pkl --dataset svhn --test_adv_dataset /home/data/maggie/result-newhome/attack/pgd/preactresnet50-svhn/20220713/00002-ompgd-eps-0.1-acc-6.73/attack-svhn-dataset/latent-attack-samples/test --batch_size 256 --epochs 40 --lr 0.01 >> /home/maggie/mmat/log/SVHN/defense/patch-mixup-training/preactresnet50-svhn-patchmixup-om-pgd-20220913.log 2>&1



# #   使用PGD对抗训练后的 cla9
# PreActResNet50 patchmixup beta(1,1) against pgd (eps=0.1)
CUDA_VISIBLE_DEVICES=1 python -u tasklauncher-20220905.py run --mode defense --defense_mode patchmixup --mix_mode maskmixup --sample_mode bernoullisampler --attack_mode pgd --attack_eps 0.1 --blackbox --exp_name preactresnet50-svhn --cla_model preactresnet50 --cla_network_pkl /home/data/maggie/result-newhome/defense/patchmixup/fgsm/maskmixup-bernoullisampler/preactresnet50-svhn/blackbox/20220914/00000/patchmixup-svhn-dataset/patchmixup-trained-classifier-preactresnet50-on-svhn-epoch-0013-patch-cla9.pkl --dataset svhn --test_adv_dataset /home/data/maggie/result-newhome/attack/pgd/preactresnet50-svhn/20220629/00002-pgd-eps-0.1-acc-35.61/attack-svhn-dataset/samples/test --batch_size 256 --epochs 40 --lr 0.01 >> /home/maggie/mmat/log/SVHN/defense/patch-mixup-training/preactresnet50-svhn-patchmixup-pgd-20220913.log 2>&1

# PreActResNet50 patchmixup beta(1,1) against autoattack (eps=0.1)
CUDA_VISIBLE_DEVICES=1 python -u tasklauncher-20220905.py run --mode defense --defense_mode patchmixup --mix_mode maskmixup --sample_mode bernoullisampler --attack_mode autoattack --attack_eps 0.1 --blackbox --exp_name preactresnet50-svhn --cla_model preactresnet50 --cla_network_pkl /home/data/maggie/result-newhome/defense/patchmixup/fgsm/maskmixup-bernoullisampler/preactresnet50-svhn/blackbox/20220914/00000/patchmixup-svhn-dataset/patchmixup-trained-classifier-preactresnet50-on-svhn-epoch-0013-patch-cla9.pkl --dataset svhn --test_adv_dataset /home/data/maggie/result-newhome/attack/autoattack/preactresnet50-svhn/20220728/00000-autoattack-eps-0.1-acc-29.94/attack-svhn-dataset/samples/test --batch_size 256 --epochs 40 --lr 0.01 >> /home/maggie/mmat/log/SVHN/defense/patch-mixup-training/preactresnet50-svhn-patchmixup-autoattack-20220913.log 2>&1

# PreActResNet50 patchmixup beta(1,1) against deepfool (eps=0.1)
CUDA_VISIBLE_DEVICES=1 python -u tasklauncher-20220905.py run --mode defense --defense_mode patchmixup --mix_mode maskmixup --sample_mode bernoullisampler --attack_mode deepfool --attack_eps 0.1 --blackbox --exp_name preactresnet50-svhn --cla_model preactresnet50 --cla_network_pkl /home/data/maggie/result-newhome/defense/patchmixup/fgsm/maskmixup-bernoullisampler/preactresnet50-svhn/blackbox/20220914/00000/patchmixup-svhn-dataset/patchmixup-trained-classifier-preactresnet50-on-svhn-epoch-0013-patch-cla9.pkl --dataset svhn --test_adv_dataset /home/data/maggie/result-newhome/attack/deepfool/preactresnet50-svhn/20220721/00000-deepfool-eps-0.1-acc-23.72/attack-svhn-dataset/samples/test --batch_size 256 --epochs 40 --lr 0.01 >> /home/maggie/mmat/log/SVHN/defense/patch-mixup-training/preactresnet50-svhn-patchmixup-deepfool-20220913.log 2>&1

# PreActResNet50 patchmixup beta(1,1) against cw (eps=0.1)
CUDA_VISIBLE_DEVICES=1 python -u tasklauncher-20220905.py run --mode defense --defense_mode patchmixup --mix_mode maskmixup --sample_mode bernoullisampler --attack_mode cw --attack_eps 0.1 --blackbox --exp_name preactresnet50-svhn --cla_model preactresnet50 --cla_network_pkl /home/data/maggie/result-newhome/defense/patchmixup/fgsm/maskmixup-bernoullisampler/preactresnet50-svhn/blackbox/20220914/00000/patchmixup-svhn-dataset/patchmixup-trained-classifier-preactresnet50-on-svhn-epoch-0013-patch-cla9.pkl --dataset svhn --test_adv_dataset /home/data/maggie/result-newhome/attack/cw/preactresnet50-svhn/20220807/00000-cw-confidence-0.0-acc-27.09/attack-svhn-dataset/samples/test --batch_size 256 --epochs 40 --lr 0.01 >> /home/maggie/mmat/log/SVHN/defense/patch-mixup-training/preactresnet50-svhn-patchmixup-cw-20220913.log 2>&1

# PreActResNet50 patchmixup beta(1,1) against om-fgsm (eps=0.1)
CUDA_VISIBLE_DEVICES=1 python -u tasklauncher-20220905.py run --mode defense --defense_mode patchmixup --mix_mode maskmixup --sample_mode bernoullisampler --attack_mode om-fgsm --attack_eps 0.1 --blackbox --exp_name preactresnet50-svhn --cla_model preactresnet50 --cla_network_pkl /home/data/maggie/result-newhome/defense/patchmixup/fgsm/maskmixup-bernoullisampler/preactresnet50-svhn/blackbox/20220914/00000/patchmixup-svhn-dataset/patchmixup-trained-classifier-preactresnet50-on-svhn-epoch-0013-patch-cla9.pkl --dataset svhn --test_adv_dataset /home/data/maggie/result-newhome/attack/fgsm/preactresnet50-svhn/20220710/00002-omfgsm-eps-0.1-acc-40.01/attack-svhn-dataset/latent-attack-samples/test --batch_size 256 --epochs 40 --lr 0.01 >> /home/maggie/mmat/log/SVHN/defense/patch-mixup-training/preactresnet50-svhn-patchmixup-om-fgsm-20220913.log 2>&1

# PreActResNet50 patchmixup beta(1,1) against om-pgd (eps=0.1)
CUDA_VISIBLE_DEVICES=1 python -u tasklauncher-20220905.py run --mode defense --defense_mode patchmixup --mix_mode maskmixup --sample_mode bernoullisampler --attack_mode om-pgd --attack_eps 0.1 --blackbox --exp_name preactresnet50-svhn --cla_model preactresnet50 --cla_network_pkl /home/data/maggie/result-newhome/defense/patchmixup/fgsm/maskmixup-bernoullisampler/preactresnet50-svhn/blackbox/20220914/00000/patchmixup-svhn-dataset/patchmixup-trained-classifier-preactresnet50-on-svhn-epoch-0013-patch-cla9.pkl --dataset svhn --test_adv_dataset /home/data/maggie/result-newhome/attack/pgd/preactresnet50-svhn/20220713/00002-ompgd-eps-0.1-acc-6.73/attack-svhn-dataset/latent-attack-samples/test --batch_size 256 --epochs 40 --lr 0.01 >> /home/maggie/mmat/log/SVHN/defense/patch-mixup-training/preactresnet50-svhn-patchmixup-om-pgd-20220913.log 2>&1



# #   使用PGD对抗训练后的 cla10
# PreActResNet50 patchmixup beta(1,1) against pgd (eps=0.1)
CUDA_VISIBLE_DEVICES=1 python -u tasklauncher-20220905.py run --mode defense --defense_mode patchmixup --mix_mode maskmixup --sample_mode bernoullisampler --attack_mode pgd --attack_eps 0.1 --blackbox --exp_name preactresnet50-svhn --cla_model preactresnet50 --cla_network_pkl /home/data/maggie/result-newhome/defense/patchmixup/fgsm/maskmixup-bernoullisampler/preactresnet50-svhn/blackbox/20220914/00000/patchmixup-svhn-dataset/patchmixup-trained-classifier-preactresnet50-on-svhn-epoch-0011-patch-cla10.pkl --dataset svhn --test_adv_dataset /home/data/maggie/result-newhome/attack/pgd/preactresnet50-svhn/20220629/00002-pgd-eps-0.1-acc-35.61/attack-svhn-dataset/samples/test --batch_size 256 --epochs 40 --lr 0.01 >> /home/maggie/mmat/log/SVHN/defense/patch-mixup-training/preactresnet50-svhn-patchmixup-pgd-20220913.log 2>&1

# PreActResNet50 patchmixup beta(1,1) against autoattack (eps=0.1)
CUDA_VISIBLE_DEVICES=1 python -u tasklauncher-20220905.py run --mode defense --defense_mode patchmixup --mix_mode maskmixup --sample_mode bernoullisampler --attack_mode autoattack --attack_eps 0.1 --blackbox --exp_name preactresnet50-svhn --cla_model preactresnet50 --cla_network_pkl /home/data/maggie/result-newhome/defense/patchmixup/fgsm/maskmixup-bernoullisampler/preactresnet50-svhn/blackbox/20220914/00000/patchmixup-svhn-dataset/patchmixup-trained-classifier-preactresnet50-on-svhn-epoch-0011-patch-cla10.pkl --dataset svhn --test_adv_dataset /home/data/maggie/result-newhome/attack/autoattack/preactresnet50-svhn/20220728/00000-autoattack-eps-0.1-acc-29.94/attack-svhn-dataset/samples/test --batch_size 256 --epochs 40 --lr 0.01 >> /home/maggie/mmat/log/SVHN/defense/patch-mixup-training/preactresnet50-svhn-patchmixup-autoattack-20220913.log 2>&1

# PreActResNet50 patchmixup beta(1,1) against deepfool (eps=0.1)
CUDA_VISIBLE_DEVICES=1 python -u tasklauncher-20220905.py run --mode defense --defense_mode patchmixup --mix_mode maskmixup --sample_mode bernoullisampler --attack_mode deepfool --attack_eps 0.1 --blackbox --exp_name preactresnet50-svhn --cla_model preactresnet50 --cla_network_pkl /home/data/maggie/result-newhome/defense/patchmixup/fgsm/maskmixup-bernoullisampler/preactresnet50-svhn/blackbox/20220914/00000/patchmixup-svhn-dataset/patchmixup-trained-classifier-preactresnet50-on-svhn-epoch-0011-patch-cla10.pkl --dataset svhn --test_adv_dataset /home/data/maggie/result-newhome/attack/deepfool/preactresnet50-svhn/20220721/00000-deepfool-eps-0.1-acc-23.72/attack-svhn-dataset/samples/test --batch_size 256 --epochs 40 --lr 0.01 >> /home/maggie/mmat/log/SVHN/defense/patch-mixup-training/preactresnet50-svhn-patchmixup-deepfool-20220913.log 2>&1

# PreActResNet50 patchmixup beta(1,1) against cw (eps=0.1)
CUDA_VISIBLE_DEVICES=1 python -u tasklauncher-20220905.py run --mode defense --defense_mode patchmixup --mix_mode maskmixup --sample_mode bernoullisampler --attack_mode cw --attack_eps 0.1 --blackbox --exp_name preactresnet50-svhn --cla_model preactresnet50 --cla_network_pkl /home/data/maggie/result-newhome/defense/patchmixup/fgsm/maskmixup-bernoullisampler/preactresnet50-svhn/blackbox/20220914/00000/patchmixup-svhn-dataset/patchmixup-trained-classifier-preactresnet50-on-svhn-epoch-0011-patch-cla10.pkl --dataset svhn --test_adv_dataset /home/data/maggie/result-newhome/attack/cw/preactresnet50-svhn/20220807/00000-cw-confidence-0.0-acc-27.09/attack-svhn-dataset/samples/test --batch_size 256 --epochs 40 --lr 0.01 >> /home/maggie/mmat/log/SVHN/defense/patch-mixup-training/preactresnet50-svhn-patchmixup-cw-20220913.log 2>&1

# PreActResNet50 patchmixup beta(1,1) against om-fgsm (eps=0.1)
CUDA_VISIBLE_DEVICES=1 python -u tasklauncher-20220905.py run --mode defense --defense_mode patchmixup --mix_mode maskmixup --sample_mode bernoullisampler --attack_mode om-fgsm --attack_eps 0.1 --blackbox --exp_name preactresnet50-svhn --cla_model preactresnet50 --cla_network_pkl /home/data/maggie/result-newhome/defense/patchmixup/fgsm/maskmixup-bernoullisampler/preactresnet50-svhn/blackbox/20220914/00000/patchmixup-svhn-dataset/patchmixup-trained-classifier-preactresnet50-on-svhn-epoch-0011-patch-cla10.pkl --dataset svhn --test_adv_dataset /home/data/maggie/result-newhome/attack/fgsm/preactresnet50-svhn/20220710/00002-omfgsm-eps-0.1-acc-40.01/attack-svhn-dataset/latent-attack-samples/test --batch_size 256 --epochs 40 --lr 0.01 >> /home/maggie/mmat/log/SVHN/defense/patch-mixup-training/preactresnet50-svhn-patchmixup-om-fgsm-20220913.log 2>&1

# PreActResNet50 patchmixup beta(1,1) against om-pgd (eps=0.1)
CUDA_VISIBLE_DEVICES=1 python -u tasklauncher-20220905.py run --mode defense --defense_mode patchmixup --mix_mode maskmixup --sample_mode bernoullisampler --attack_mode om-pgd --attack_eps 0.1 --blackbox --exp_name preactresnet50-svhn --cla_model preactresnet50 --cla_network_pkl /home/data/maggie/result-newhome/defense/patchmixup/fgsm/maskmixup-bernoullisampler/preactresnet50-svhn/blackbox/20220914/00000/patchmixup-svhn-dataset/patchmixup-trained-classifier-preactresnet50-on-svhn-epoch-0011-patch-cla10.pkl --dataset svhn --test_adv_dataset /home/data/maggie/result-newhome/attack/pgd/preactresnet50-svhn/20220713/00002-ompgd-eps-0.1-acc-6.73/attack-svhn-dataset/latent-attack-samples/test --batch_size 256 --epochs 40 --lr 0.01 >> /home/maggie/mmat/log/SVHN/defense/patch-mixup-training/preactresnet50-svhn-patchmixup-om-pgd-20220913.log 2>&1



# #   使用PGD对抗训练后的 cla11
# PreActResNet50 patchmixup beta(1,1) against pgd (eps=0.1)
CUDA_VISIBLE_DEVICES=1 python -u tasklauncher-20220905.py run --mode defense --defense_mode patchmixup --mix_mode maskmixup --sample_mode bernoullisampler --attack_mode pgd --attack_eps 0.1 --blackbox --exp_name preactresnet50-svhn --cla_model preactresnet50 --cla_network_pkl /home/data/maggie/result-newhome/defense/patchmixup/fgsm/maskmixup-bernoullisampler/preactresnet50-svhn/blackbox/20220914/00000/patchmixup-svhn-dataset/patchmixup-trained-classifier-preactresnet50-on-svhn-epoch-0012-patch-cla11.pkl --dataset svhn --test_adv_dataset /home/data/maggie/result-newhome/attack/pgd/preactresnet50-svhn/20220629/00002-pgd-eps-0.1-acc-35.61/attack-svhn-dataset/samples/test --batch_size 256 --epochs 40 --lr 0.01 >> /home/maggie/mmat/log/SVHN/defense/patch-mixup-training/preactresnet50-svhn-patchmixup-pgd-20220913.log 2>&1

# PreActResNet50 patchmixup beta(1,1) against autoattack (eps=0.1)
CUDA_VISIBLE_DEVICES=1 python -u tasklauncher-20220905.py run --mode defense --defense_mode patchmixup --mix_mode maskmixup --sample_mode bernoullisampler --attack_mode autoattack --attack_eps 0.1 --blackbox --exp_name preactresnet50-svhn --cla_model preactresnet50 --cla_network_pkl /home/data/maggie/result-newhome/defense/patchmixup/fgsm/maskmixup-bernoullisampler/preactresnet50-svhn/blackbox/20220914/00000/patchmixup-svhn-dataset/patchmixup-trained-classifier-preactresnet50-on-svhn-epoch-0012-patch-cla11.pkl --dataset svhn --test_adv_dataset /home/data/maggie/result-newhome/attack/autoattack/preactresnet50-svhn/20220728/00000-autoattack-eps-0.1-acc-29.94/attack-svhn-dataset/samples/test --batch_size 256 --epochs 40 --lr 0.01 >> /home/maggie/mmat/log/SVHN/defense/patch-mixup-training/preactresnet50-svhn-patchmixup-autoattack-20220913.log 2>&1

# PreActResNet50 patchmixup beta(1,1) against deepfool (eps=0.1)
CUDA_VISIBLE_DEVICES=1 python -u tasklauncher-20220905.py run --mode defense --defense_mode patchmixup --mix_mode maskmixup --sample_mode bernoullisampler --attack_mode deepfool --attack_eps 0.1 --blackbox --exp_name preactresnet50-svhn --cla_model preactresnet50 --cla_network_pkl /home/data/maggie/result-newhome/defense/patchmixup/fgsm/maskmixup-bernoullisampler/preactresnet50-svhn/blackbox/20220914/00000/patchmixup-svhn-dataset/patchmixup-trained-classifier-preactresnet50-on-svhn-epoch-0012-patch-cla11.pkl --dataset svhn --test_adv_dataset /home/data/maggie/result-newhome/attack/deepfool/preactresnet50-svhn/20220721/00000-deepfool-eps-0.1-acc-23.72/attack-svhn-dataset/samples/test --batch_size 256 --epochs 40 --lr 0.01 >> /home/maggie/mmat/log/SVHN/defense/patch-mixup-training/preactresnet50-svhn-patchmixup-deepfool-20220913.log 2>&1

# PreActResNet50 patchmixup beta(1,1) against cw (eps=0.1)
CUDA_VISIBLE_DEVICES=1 python -u tasklauncher-20220905.py run --mode defense --defense_mode patchmixup --mix_mode maskmixup --sample_mode bernoullisampler --attack_mode cw --attack_eps 0.1 --blackbox --exp_name preactresnet50-svhn --cla_model preactresnet50 --cla_network_pkl /home/data/maggie/result-newhome/defense/patchmixup/fgsm/maskmixup-bernoullisampler/preactresnet50-svhn/blackbox/20220914/00000/patchmixup-svhn-dataset/patchmixup-trained-classifier-preactresnet50-on-svhn-epoch-0012-patch-cla11.pkl --dataset svhn --test_adv_dataset /home/data/maggie/result-newhome/attack/cw/preactresnet50-svhn/20220807/00000-cw-confidence-0.0-acc-27.09/attack-svhn-dataset/samples/test --batch_size 256 --epochs 40 --lr 0.01 >> /home/maggie/mmat/log/SVHN/defense/patch-mixup-training/preactresnet50-svhn-patchmixup-cw-20220913.log 2>&1

# PreActResNet50 patchmixup beta(1,1) against om-fgsm (eps=0.1)
CUDA_VISIBLE_DEVICES=1 python -u tasklauncher-20220905.py run --mode defense --defense_mode patchmixup --mix_mode maskmixup --sample_mode bernoullisampler --attack_mode om-fgsm --attack_eps 0.1 --blackbox --exp_name preactresnet50-svhn --cla_model preactresnet50 --cla_network_pkl /home/data/maggie/result-newhome/defense/patchmixup/fgsm/maskmixup-bernoullisampler/preactresnet50-svhn/blackbox/20220914/00000/patchmixup-svhn-dataset/patchmixup-trained-classifier-preactresnet50-on-svhn-epoch-0012-patch-cla11.pkl --dataset svhn --test_adv_dataset /home/data/maggie/result-newhome/attack/fgsm/preactresnet50-svhn/20220710/00002-omfgsm-eps-0.1-acc-40.01/attack-svhn-dataset/latent-attack-samples/test --batch_size 256 --epochs 40 --lr 0.01 >> /home/maggie/mmat/log/SVHN/defense/patch-mixup-training/preactresnet50-svhn-patchmixup-om-fgsm-20220913.log 2>&1

# PreActResNet50 patchmixup beta(1,1) against om-pgd (eps=0.1)
CUDA_VISIBLE_DEVICES=1 python -u tasklauncher-20220905.py run --mode defense --defense_mode patchmixup --mix_mode maskmixup --sample_mode bernoullisampler --attack_mode om-pgd --attack_eps 0.1 --blackbox --exp_name preactresnet50-svhn --cla_model preactresnet50 --cla_network_pkl /home/data/maggie/result-newhome/defense/patchmixup/fgsm/maskmixup-bernoullisampler/preactresnet50-svhn/blackbox/20220914/00000/patchmixup-svhn-dataset/patchmixup-trained-classifier-preactresnet50-on-svhn-epoch-0012-patch-cla11.pkl --dataset svhn --test_adv_dataset /home/data/maggie/result-newhome/attack/pgd/preactresnet50-svhn/20220713/00002-ompgd-eps-0.1-acc-6.73/attack-svhn-dataset/latent-attack-samples/test --batch_size 256 --epochs 40 --lr 0.01 >> /home/maggie/mmat/log/SVHN/defense/patch-mixup-training/preactresnet50-svhn-patchmixup-om-pgd-20220913.log 2>&1


# #   使用PGD对抗训练后的 cla12
# PreActResNet50 patchmixup beta(1,1) against pgd (eps=0.1)
CUDA_VISIBLE_DEVICES=1 python -u tasklauncher-20220905.py run --mode defense --defense_mode patchmixup --mix_mode maskmixup --sample_mode bernoullisampler --attack_mode pgd --attack_eps 0.1 --blackbox --exp_name preactresnet50-svhn --cla_model preactresnet50 --cla_network_pkl /home/data/maggie/result-newhome/defense/patchmixup/fgsm/maskmixup-bernoullisampler/preactresnet50-svhn/blackbox/20220914/00000/patchmixup-svhn-dataset/patchmixup-trained-classifier-preactresnet50-on-svhn-epoch-0014-patch-cla12.pkl --dataset svhn --test_adv_dataset /home/data/maggie/result-newhome/attack/pgd/preactresnet50-svhn/20220629/00002-pgd-eps-0.1-acc-35.61/attack-svhn-dataset/samples/test --batch_size 256 --epochs 40 --lr 0.01 >> /home/maggie/mmat/log/SVHN/defense/patch-mixup-training/preactresnet50-svhn-patchmixup-pgd-20220913.log 2>&1

# PreActResNet50 patchmixup beta(1,1) against autoattack (eps=0.1)
CUDA_VISIBLE_DEVICES=1 python -u tasklauncher-20220905.py run --mode defense --defense_mode patchmixup --mix_mode maskmixup --sample_mode bernoullisampler --attack_mode autoattack --attack_eps 0.1 --blackbox --exp_name preactresnet50-svhn --cla_model preactresnet50 --cla_network_pkl /home/data/maggie/result-newhome/defense/patchmixup/fgsm/maskmixup-bernoullisampler/preactresnet50-svhn/blackbox/20220914/00000/patchmixup-svhn-dataset/patchmixup-trained-classifier-preactresnet50-on-svhn-epoch-0014-patch-cla12.pkl --dataset svhn --test_adv_dataset /home/data/maggie/result-newhome/attack/autoattack/preactresnet50-svhn/20220728/00000-autoattack-eps-0.1-acc-29.94/attack-svhn-dataset/samples/test --batch_size 256 --epochs 40 --lr 0.01 >> /home/maggie/mmat/log/SVHN/defense/patch-mixup-training/preactresnet50-svhn-patchmixup-autoattack-20220913.log 2>&1

# PreActResNet50 patchmixup beta(1,1) against deepfool (eps=0.1)
CUDA_VISIBLE_DEVICES=1 python -u tasklauncher-20220905.py run --mode defense --defense_mode patchmixup --mix_mode maskmixup --sample_mode bernoullisampler --attack_mode deepfool --attack_eps 0.1 --blackbox --exp_name preactresnet50-svhn --cla_model preactresnet50 --cla_network_pkl /home/data/maggie/result-newhome/defense/patchmixup/fgsm/maskmixup-bernoullisampler/preactresnet50-svhn/blackbox/20220914/00000/patchmixup-svhn-dataset/patchmixup-trained-classifier-preactresnet50-on-svhn-epoch-0014-patch-cla12.pkl --dataset svhn --test_adv_dataset /home/data/maggie/result-newhome/attack/deepfool/preactresnet50-svhn/20220721/00000-deepfool-eps-0.1-acc-23.72/attack-svhn-dataset/samples/test --batch_size 256 --epochs 40 --lr 0.01 >> /home/maggie/mmat/log/SVHN/defense/patch-mixup-training/preactresnet50-svhn-patchmixup-deepfool-20220913.log 2>&1

# PreActResNet50 patchmixup beta(1,1) against cw (eps=0.1)
CUDA_VISIBLE_DEVICES=1 python -u tasklauncher-20220905.py run --mode defense --defense_mode patchmixup --mix_mode maskmixup --sample_mode bernoullisampler --attack_mode cw --attack_eps 0.1 --blackbox --exp_name preactresnet50-svhn --cla_model preactresnet50 --cla_network_pkl /home/data/maggie/result-newhome/defense/patchmixup/fgsm/maskmixup-bernoullisampler/preactresnet50-svhn/blackbox/20220914/00000/patchmixup-svhn-dataset/patchmixup-trained-classifier-preactresnet50-on-svhn-epoch-0014-patch-cla12.pkl --dataset svhn --test_adv_dataset /home/data/maggie/result-newhome/attack/cw/preactresnet50-svhn/20220807/00000-cw-confidence-0.0-acc-27.09/attack-svhn-dataset/samples/test --batch_size 256 --epochs 40 --lr 0.01 >> /home/maggie/mmat/log/SVHN/defense/patch-mixup-training/preactresnet50-svhn-patchmixup-cw-20220913.log 2>&1

# PreActResNet50 patchmixup beta(1,1) against om-fgsm (eps=0.1)
CUDA_VISIBLE_DEVICES=1 python -u tasklauncher-20220905.py run --mode defense --defense_mode patchmixup --mix_mode maskmixup --sample_mode bernoullisampler --attack_mode om-fgsm --attack_eps 0.1 --blackbox --exp_name preactresnet50-svhn --cla_model preactresnet50 --cla_network_pkl /home/data/maggie/result-newhome/defense/patchmixup/fgsm/maskmixup-bernoullisampler/preactresnet50-svhn/blackbox/20220914/00000/patchmixup-svhn-dataset/patchmixup-trained-classifier-preactresnet50-on-svhn-epoch-0014-patch-cla12.pkl --dataset svhn --test_adv_dataset /home/data/maggie/result-newhome/attack/fgsm/preactresnet50-svhn/20220710/00002-omfgsm-eps-0.1-acc-40.01/attack-svhn-dataset/latent-attack-samples/test --batch_size 256 --epochs 40 --lr 0.01 >> /home/maggie/mmat/log/SVHN/defense/patch-mixup-training/preactresnet50-svhn-patchmixup-om-fgsm-20220913.log 2>&1

# PreActResNet50 patchmixup beta(1,1) against om-pgd (eps=0.1)
CUDA_VISIBLE_DEVICES=1 python -u tasklauncher-20220905.py run --mode defense --defense_mode patchmixup --mix_mode maskmixup --sample_mode bernoullisampler --attack_mode om-pgd --attack_eps 0.1 --blackbox --exp_name preactresnet50-svhn --cla_model preactresnet50 --cla_network_pkl /home/data/maggie/result-newhome/defense/patchmixup/fgsm/maskmixup-bernoullisampler/preactresnet50-svhn/blackbox/20220914/00000/patchmixup-svhn-dataset/patchmixup-trained-classifier-preactresnet50-on-svhn-epoch-0014-patch-cla12.pkl --dataset svhn --test_adv_dataset /home/data/maggie/result-newhome/attack/pgd/preactresnet50-svhn/20220713/00002-ompgd-eps-0.1-acc-6.73/attack-svhn-dataset/latent-attack-samples/test --batch_size 256 --epochs 40 --lr 0.01 >> /home/maggie/mmat/log/SVHN/defense/patch-mixup-training/preactresnet50-svhn-patchmixup-om-pgd-20220913.log 2>&1


# #   使用PGD对抗训练后的 cla13
# PreActResNet50 patchmixup beta(1,1) against pgd (eps=0.1)
CUDA_VISIBLE_DEVICES=1 python -u tasklauncher-20220905.py run --mode defense --defense_mode patchmixup --mix_mode maskmixup --sample_mode bernoullisampler --attack_mode pgd --attack_eps 0.1 --blackbox --exp_name preactresnet50-svhn --cla_model preactresnet50 --cla_network_pkl /home/data/maggie/result-newhome/defense/patchmixup/fgsm/maskmixup-bernoullisampler/preactresnet50-svhn/blackbox/20220914/00000/patchmixup-svhn-dataset/patchmixup-trained-classifier-preactresnet50-on-svhn-epoch-0015-patch-cla13.pkl --dataset svhn --test_adv_dataset /home/data/maggie/result-newhome/attack/pgd/preactresnet50-svhn/20220629/00002-pgd-eps-0.1-acc-35.61/attack-svhn-dataset/samples/test --batch_size 256 --epochs 40 --lr 0.01 >> /home/maggie/mmat/log/SVHN/defense/patch-mixup-training/preactresnet50-svhn-patchmixup-pgd-20220913.log 2>&1

# PreActResNet50 patchmixup beta(1,1) against autoattack (eps=0.1)
CUDA_VISIBLE_DEVICES=1 python -u tasklauncher-20220905.py run --mode defense --defense_mode patchmixup --mix_mode maskmixup --sample_mode bernoullisampler --attack_mode autoattack --attack_eps 0.1 --blackbox --exp_name preactresnet50-svhn --cla_model preactresnet50 --cla_network_pkl /home/data/maggie/result-newhome/defense/patchmixup/fgsm/maskmixup-bernoullisampler/preactresnet50-svhn/blackbox/20220914/00000/patchmixup-svhn-dataset/patchmixup-trained-classifier-preactresnet50-on-svhn-epoch-0015-patch-cla13.pkl --dataset svhn --test_adv_dataset /home/data/maggie/result-newhome/attack/autoattack/preactresnet50-svhn/20220728/00000-autoattack-eps-0.1-acc-29.94/attack-svhn-dataset/samples/test --batch_size 256 --epochs 40 --lr 0.01 >> /home/maggie/mmat/log/SVHN/defense/patch-mixup-training/preactresnet50-svhn-patchmixup-autoattack-20220913.log 2>&1

# PreActResNet50 patchmixup beta(1,1) against deepfool (eps=0.1)
CUDA_VISIBLE_DEVICES=1 python -u tasklauncher-20220905.py run --mode defense --defense_mode patchmixup --mix_mode maskmixup --sample_mode bernoullisampler --attack_mode deepfool --attack_eps 0.1 --blackbox --exp_name preactresnet50-svhn --cla_model preactresnet50 --cla_network_pkl /home/data/maggie/result-newhome/defense/patchmixup/fgsm/maskmixup-bernoullisampler/preactresnet50-svhn/blackbox/20220914/00000/patchmixup-svhn-dataset/patchmixup-trained-classifier-preactresnet50-on-svhn-epoch-0015-patch-cla13.pkl --dataset svhn --test_adv_dataset /home/data/maggie/result-newhome/attack/deepfool/preactresnet50-svhn/20220721/00000-deepfool-eps-0.1-acc-23.72/attack-svhn-dataset/samples/test --batch_size 256 --epochs 40 --lr 0.01 >> /home/maggie/mmat/log/SVHN/defense/patch-mixup-training/preactresnet50-svhn-patchmixup-deepfool-20220913.log 2>&1

# PreActResNet50 patchmixup beta(1,1) against cw (eps=0.1)
CUDA_VISIBLE_DEVICES=1 python -u tasklauncher-20220905.py run --mode defense --defense_mode patchmixup --mix_mode maskmixup --sample_mode bernoullisampler --attack_mode cw --attack_eps 0.1 --blackbox --exp_name preactresnet50-svhn --cla_model preactresnet50 --cla_network_pkl /home/data/maggie/result-newhome/defense/patchmixup/fgsm/maskmixup-bernoullisampler/preactresnet50-svhn/blackbox/20220914/00000/patchmixup-svhn-dataset/patchmixup-trained-classifier-preactresnet50-on-svhn-epoch-0015-patch-cla13.pkl --dataset svhn --test_adv_dataset /home/data/maggie/result-newhome/attack/cw/preactresnet50-svhn/20220807/00000-cw-confidence-0.0-acc-27.09/attack-svhn-dataset/samples/test --batch_size 256 --epochs 40 --lr 0.01 >> /home/maggie/mmat/log/SVHN/defense/patch-mixup-training/preactresnet50-svhn-patchmixup-cw-20220913.log 2>&1

# PreActResNet50 patchmixup beta(1,1) against om-fgsm (eps=0.1)
CUDA_VISIBLE_DEVICES=1 python -u tasklauncher-20220905.py run --mode defense --defense_mode patchmixup --mix_mode maskmixup --sample_mode bernoullisampler --attack_mode om-fgsm --attack_eps 0.1 --blackbox --exp_name preactresnet50-svhn --cla_model preactresnet50 --cla_network_pkl /home/data/maggie/result-newhome/defense/patchmixup/fgsm/maskmixup-bernoullisampler/preactresnet50-svhn/blackbox/20220914/00000/patchmixup-svhn-dataset/patchmixup-trained-classifier-preactresnet50-on-svhn-epoch-0015-patch-cla13.pkl --dataset svhn --test_adv_dataset /home/data/maggie/result-newhome/attack/fgsm/preactresnet50-svhn/20220710/00002-omfgsm-eps-0.1-acc-40.01/attack-svhn-dataset/latent-attack-samples/test --batch_size 256 --epochs 40 --lr 0.01 >> /home/maggie/mmat/log/SVHN/defense/patch-mixup-training/preactresnet50-svhn-patchmixup-om-fgsm-20220913.log 2>&1

# PreActResNet50 patchmixup beta(1,1) against om-pgd (eps=0.1)
CUDA_VISIBLE_DEVICES=1 python -u tasklauncher-20220905.py run --mode defense --defense_mode patchmixup --mix_mode maskmixup --sample_mode bernoullisampler --attack_mode om-pgd --attack_eps 0.1 --blackbox --exp_name preactresnet50-svhn --cla_model preactresnet50 --cla_network_pkl /home/data/maggie/result-newhome/defense/patchmixup/fgsm/maskmixup-bernoullisampler/preactresnet50-svhn/blackbox/20220914/00000/patchmixup-svhn-dataset/patchmixup-trained-classifier-preactresnet50-on-svhn-epoch-0015-patch-cla13.pkl --dataset svhn --test_adv_dataset /home/data/maggie/result-newhome/attack/pgd/preactresnet50-svhn/20220713/00002-ompgd-eps-0.1-acc-6.73/attack-svhn-dataset/latent-attack-samples/test --batch_size 256 --epochs 40 --lr 0.01 >> /home/maggie/mmat/log/SVHN/defense/patch-mixup-training/preactresnet50-svhn-patchmixup-om-pgd-20220913.log 2>&1



