source ~/.bashrc
source /home/xieyi/anaconda3/bin/activate mmat

# # adv50000 cat cle50000
# # PreActResNet34 manifoldmixup beta(1,1) against FGSM (eps=0.1)
# CUDA_VISIBLE_DEVICES=0 python -u tasklauncher-20220905.py run --mode defense --defense_mode manifoldmixup --beta_alpha 1 --mix_mode basemixup --sample_mode betasampler --attack_mode fgsm --attack_eps 0.1 --blackbox --exp_name preactresnet34-svhn --cla_model preactresnet34 --cla_network_pkl /home/data/maggie/result-newhome/train/cla-train/preactresnet34-svhn/20220627/00003-testacc-95.75/train-svhn-dataset/standard-trained-classifier-preactresnet34-on-clean-svhn-epoch-0013.pkl --dataset svhn --test_adv_dataset /home/data/maggie/result-newhome/attack/fgsm/preactresnet34-svhn/20220628/00002-fgsm-eps-0.1-acc-57.11/attack-svhn-dataset/samples/test --batch_size 256 --epochs 40 --lr 0.01 >> /home/maggie/mmat/log/SVHN/defense/manifold-mixup-training/preactresnet34-svhn-manifoldmixup-fgsm-20220916.log 2>&1

# # PreActResNet34 manifoldmixup beta(1,1) against FGSM (eps=0.1)
# CUDA_VISIBLE_DEVICES=0 python -u tasklauncher-20220905.py run --mode defense --defense_mode manifoldmixup --beta_alpha 1 --mix_mode basemixup --sample_mode betasampler --attack_mode fgsm --attack_eps 0.1 --blackbox --exp_name preactresnet34-svhn --cla_model preactresnet34 --cla_network_pkl /home/data/maggie/result-newhome/train/cla-train/preactresnet34-svhn/20220627/00003-testacc-95.75/train-svhn-dataset/standard-trained-classifier-preactresnet34-on-clean-svhn-epoch-0013.pkl --dataset svhn --test_adv_dataset /home/data/maggie/result-newhome/attack/fgsm/preactresnet34-svhn/20220628/00002-fgsm-eps-0.1-acc-57.11/attack-svhn-dataset/samples/test --batch_size 256 --epochs 40 --lr 0.01 >> /home/maggie/mmat/log/SVHN/defense/manifold-mixup-training/preactresnet34-svhn-manifoldmixup-fgsm-20220916.log 2>&1

# # PreActResNet34 manifoldmixup beta(1,1) against FGSM (eps=0.1)
# CUDA_VISIBLE_DEVICES=0 python -u tasklauncher-20220905.py run --mode defense --defense_mode manifoldmixup --beta_alpha 1 --mix_mode basemixup --sample_mode betasampler --attack_mode fgsm --attack_eps 0.1 --blackbox --exp_name preactresnet34-svhn --cla_model preactresnet34 --cla_network_pkl /home/data/maggie/result-newhome/train/cla-train/preactresnet34-svhn/20220627/00003-testacc-95.75/train-svhn-dataset/standard-trained-classifier-preactresnet34-on-clean-svhn-epoch-0013.pkl --dataset svhn --test_adv_dataset /home/data/maggie/result-newhome/attack/fgsm/preactresnet34-svhn/20220628/00002-fgsm-eps-0.1-acc-57.11/attack-svhn-dataset/samples/test --batch_size 256 --epochs 40 --lr 0.01 >> /home/maggie/mmat/log/SVHN/defense/manifold-mixup-training/preactresnet34-svhn-manifoldmixup-fgsm-20220916.log 2>&1

# # PreActResNet34 manifoldmixup beta(1,1) against FGSM (eps=0.1)
# CUDA_VISIBLE_DEVICES=0 python -u tasklauncher-20220905.py run --mode defense --defense_mode manifoldmixup --beta_alpha 1 --mix_mode basemixup --sample_mode betasampler --attack_mode fgsm --attack_eps 0.1 --blackbox --exp_name preactresnet34-svhn --cla_model preactresnet34 --cla_network_pkl /home/data/maggie/result-newhome/train/cla-train/preactresnet34-svhn/20220627/00003-testacc-95.75/train-svhn-dataset/standard-trained-classifier-preactresnet34-on-clean-svhn-epoch-0013.pkl --dataset svhn --test_adv_dataset /home/data/maggie/result-newhome/attack/fgsm/preactresnet34-svhn/20220628/00002-fgsm-eps-0.1-acc-57.11/attack-svhn-dataset/samples/test --batch_size 256 --epochs 40 --lr 0.01 >> /home/maggie/mmat/log/SVHN/defense/manifold-mixup-training/preactresnet34-svhn-manifoldmixup-fgsm-20220916.log 2>&1

# # PreActResNet34 manifoldmixup beta(1,1) against FGSM (eps=0.1)
# CUDA_VISIBLE_DEVICES=0 python -u tasklauncher-20220905.py run --mode defense --defense_mode manifoldmixup --beta_alpha 1 --mix_mode basemixup --sample_mode betasampler --attack_mode fgsm --attack_eps 0.1 --blackbox --exp_name preactresnet34-svhn --cla_model preactresnet34 --cla_network_pkl /home/data/maggie/result-newhome/train/cla-train/preactresnet34-svhn/20220627/00003-testacc-95.75/train-svhn-dataset/standard-trained-classifier-preactresnet34-on-clean-svhn-epoch-0013.pkl --dataset svhn --test_adv_dataset /home/data/maggie/result-newhome/attack/fgsm/preactresnet34-svhn/20220628/00002-fgsm-eps-0.1-acc-57.11/attack-svhn-dataset/samples/test --batch_size 256 --epochs 40 --lr 0.01 >> /home/maggie/mmat/log/SVHN/defense/manifold-mixup-training/preactresnet34-svhn-manifoldmixup-fgsm-20220916.log 2>&1

# # PreActResNet34 manifoldmixup beta(1,1) against FGSM (eps=0.1)
# CUDA_VISIBLE_DEVICES=0 python -u tasklauncher-20220905.py run --mode defense --defense_mode manifoldmixup --beta_alpha 1 --mix_mode basemixup --sample_mode betasampler --attack_mode fgsm --attack_eps 0.1 --blackbox --exp_name preactresnet34-svhn --cla_model preactresnet34 --cla_network_pkl /home/data/maggie/result-newhome/train/cla-train/preactresnet34-svhn/20220627/00003-testacc-95.75/train-svhn-dataset/standard-trained-classifier-preactresnet34-on-clean-svhn-epoch-0013.pkl --dataset svhn --test_adv_dataset /home/data/maggie/result-newhome/attack/fgsm/preactresnet34-svhn/20220628/00002-fgsm-eps-0.1-acc-57.11/attack-svhn-dataset/samples/test --batch_size 256 --epochs 40 --lr 0.01 >> /home/maggie/mmat/log/SVHN/defense/manifold-mixup-training/preactresnet34-svhn-manifoldmixup-fgsm-20220916.log 2>&1

# #-------------以上要存储at训练好的模型-----------
# # #   使用PGD对抗训练后的 cla1
# # PreActResNet34 manifoldmixup beta(1,1) against pgd (eps=0.1)
# CUDA_VISIBLE_DEVICES=0 python -u tasklauncher-20220905.py run --mode defense --defense_mode manifoldmixup --beta_alpha 1 --mix_mode basemixup --sample_mode betasampler --attack_mode pgd --attack_eps 0.1 --blackbox --exp_name preactresnet34-svhn --cla_model preactresnet34 --cla_network_pkl /home/data/maggie/result-newhome/defense/manifoldmixup/fgsm/basemixup-betasampler/preactresnet34-svhn/blackbox/20220902/00005/manifoldmixup-svhn-dataset/manifoldmixup-trained-classifier-preactresnet34-on-svhn-epoch-0006-manifoldmix-cla1.pkl --dataset svhn --test_adv_dataset /home/data/maggie/result-newhome/attack/pgd/preactresnet34-svhn/20220629/00002-pgd-eps-0.1-acc-35.57/attack-svhn-dataset/samples/test --batch_size 256 --epochs 40 --lr 0.01 >> /home/maggie/mmat/log/SVHN/defense/manifold-mixup-training/preactresnet34-svhn-manifoldmixup-pgd-20220916.log 2>&1

# # PreActResNet34 manifoldmixup beta(1,1) against autoattack (eps=0.1)
# CUDA_VISIBLE_DEVICES=0 python -u tasklauncher-20220905.py run --mode defense --defense_mode manifoldmixup --beta_alpha 1 --mix_mode basemixup --sample_mode betasampler --attack_mode autoattack --attack_eps 0.1 --blackbox --exp_name preactresnet34-svhn --cla_model preactresnet34 --cla_network_pkl /home/data/maggie/result-newhome/defense/manifoldmixup/fgsm/basemixup-betasampler/preactresnet34-svhn/blackbox/20220902/00005/manifoldmixup-svhn-dataset/manifoldmixup-trained-classifier-preactresnet34-on-svhn-epoch-0006-manifoldmix-cla1.pkl --dataset svhn --test_adv_dataset /home/data/maggie/result-newhome/attack/autoattack/preactresnet34-svhn/20220724/00000-autoattack-eps-0.1-acc-29.80/attack-svhn-dataset/samples/test --batch_size 256 --epochs 40 --lr 0.01 >> /home/maggie/mmat/log/SVHN/defense/manifold-mixup-training/preactresnet34-svhn-manifoldmixup-autoattack-20220916.log 2>&1

# # PreActResNet34 manifoldmixup beta(1,1) against deepfool (eps=0.1)
# CUDA_VISIBLE_DEVICES=0 python -u tasklauncher-20220905.py run --mode defense --defense_mode manifoldmixup --beta_alpha 1 --mix_mode basemixup --sample_mode betasampler --attack_mode deepfool --attack_eps 0.1 --blackbox --exp_name preactresnet34-svhn --cla_model preactresnet34 --cla_network_pkl /home/data/maggie/result-newhome/defense/manifoldmixup/fgsm/basemixup-betasampler/preactresnet34-svhn/blackbox/20220902/00005/manifoldmixup-svhn-dataset/manifoldmixup-trained-classifier-preactresnet34-on-svhn-epoch-0006-manifoldmix-cla1.pkl --dataset svhn --test_adv_dataset /home/data/maggie/result-newhome/attack/deepfool/preactresnet34-svhn/20220720/00000-deepfool-eps-0.1-acc-19.94/attack-svhn-dataset/samples/test --batch_size 256 --epochs 40 --lr 0.01 >> /home/maggie/mmat/log/SVHN/defense/manifold-mixup-training/preactresnet34-svhn-manifoldmixup-deepfool-20220916.log 2>&1

# # PreActResNet34 manifoldmixup beta(1,1) against cw (eps=0.1)
# CUDA_VISIBLE_DEVICES=0 python -u tasklauncher-20220905.py run --mode defense --defense_mode manifoldmixup --beta_alpha 1 --mix_mode basemixup --sample_mode betasampler --attack_mode cw --attack_eps 0.1 --blackbox --exp_name preactresnet34-svhn --cla_model preactresnet34 --cla_network_pkl /home/data/maggie/result-newhome/defense/manifoldmixup/fgsm/basemixup-betasampler/preactresnet34-svhn/blackbox/20220902/00005/manifoldmixup-svhn-dataset/manifoldmixup-trained-classifier-preactresnet34-on-svhn-epoch-0006-manifoldmix-cla1.pkl --dataset svhn --test_adv_dataset /home/data/maggie/result-newhome/attack/cw/preactresnet34-svhn/20220708/00000-cw-confidence-0.0-acc-25.62/attack-svhn-dataset/samples/test --batch_size 256 --epochs 40 --lr 0.01 >> /home/maggie/mmat/log/SVHN/defense/manifold-mixup-training/preactresnet34-svhn-manifoldmixup-cw-20220916.log 2>&1

# # PreActResNet34 manifoldmixup beta(1,1) against om-fgsm (eps=0.1)
# CUDA_VISIBLE_DEVICES=0 python -u tasklauncher-20220905.py run --mode defense --defense_mode manifoldmixup --beta_alpha 1 --mix_mode basemixup --sample_mode betasampler --attack_mode om-fgsm --attack_eps 0.1 --blackbox --exp_name preactresnet34-svhn --cla_model preactresnet34 --cla_network_pkl /home/data/maggie/result-newhome/defense/manifoldmixup/fgsm/basemixup-betasampler/preactresnet34-svhn/blackbox/20220902/00005/manifoldmixup-svhn-dataset/manifoldmixup-trained-classifier-preactresnet34-on-svhn-epoch-0006-manifoldmix-cla1.pkl --dataset svhn --test_adv_dataset /home/data/maggie/result-newhome/attack/fgsm/preactresnet34-svhn/20220710/00002-omfgsm-eps-0.1-acc-36.62/attack-svhn-dataset/latent-attack-samples/test --batch_size 256 --epochs 40 --lr 0.01 >> /home/maggie/mmat/log/SVHN/defense/manifold-mixup-training/preactresnet34-svhn-manifoldmixup-om-fgsm-20220916.log 2>&1

# # PreActResNet34 manifoldmixup beta(1,1) against om-pgd (eps=0.1)
# CUDA_VISIBLE_DEVICES=0 python -u tasklauncher-20220905.py run --mode defense --defense_mode manifoldmixup --beta_alpha 1 --mix_mode basemixup --sample_mode betasampler --attack_mode om-pgd --attack_eps 0.1 --blackbox --exp_name preactresnet34-svhn --cla_model preactresnet34 --cla_network_pkl /home/data/maggie/result-newhome/defense/manifoldmixup/fgsm/basemixup-betasampler/preactresnet34-svhn/blackbox/20220902/00005/manifoldmixup-svhn-dataset/manifoldmixup-trained-classifier-preactresnet34-on-svhn-epoch-0006-manifoldmix-cla1.pkl --dataset svhn --test_adv_dataset /home/data/maggie/result-newhome/attack/pgd/preactresnet34-svhn/20220712/00002-ompgd-eps-0.1-acc-5.01/attack-svhn-dataset/latent-attack-samples/test --batch_size 256 --epochs 40 --lr 0.01 >> /home/maggie/mmat/log/SVHN/defense/manifold-mixup-training/preactresnet34-svhn-manifoldmixup-om-pgd-20220916.log 2>&1

# # #   使用PGD对抗训练后的 cla2
# # PreActResNet34 manifoldmixup beta(1,1) against pgd (eps=0.1)
# CUDA_VISIBLE_DEVICES=0 python -u tasklauncher-20220905.py run --mode defense --defense_mode manifoldmixup --beta_alpha 1 --mix_mode basemixup --sample_mode betasampler --attack_mode pgd --attack_eps 0.1 --blackbox --exp_name preactresnet34-svhn --cla_model preactresnet34 --cla_network_pkl /home/data/maggie/result-newhome/defense/manifoldmixup/fgsm/basemixup-betasampler/preactresnet34-svhn/blackbox/20220902/00006/manifoldmixup-svhn-dataset/manifoldmixup-trained-classifier-preactresnet34-on-svhn-epoch-0006manifoldmix-cla2.pkl --dataset svhn --test_adv_dataset /home/data/maggie/result-newhome/attack/pgd/preactresnet34-svhn/20220629/00002-pgd-eps-0.1-acc-35.57/attack-svhn-dataset/samples/test --batch_size 256 --epochs 40 --lr 0.01 >> /home/maggie/mmat/log/SVHN/defense/manifold-mixup-training/preactresnet34-svhn-manifoldmixup-pgd-20220916.log 2>&1

# # PreActResNet34 manifoldmixup beta(1,1) against autoattack (eps=0.1)
# CUDA_VISIBLE_DEVICES=0 python -u tasklauncher-20220905.py run --mode defense --defense_mode manifoldmixup --beta_alpha 1 --mix_mode basemixup --sample_mode betasampler --attack_mode autoattack --attack_eps 0.1 --blackbox --exp_name preactresnet34-svhn --cla_model preactresnet34 --cla_network_pkl /home/data/maggie/result-newhome/defense/manifoldmixup/fgsm/basemixup-betasampler/preactresnet34-svhn/blackbox/20220902/00006/manifoldmixup-svhn-dataset/manifoldmixup-trained-classifier-preactresnet34-on-svhn-epoch-0006manifoldmix-cla2.pkl --dataset svhn --test_adv_dataset /home/data/maggie/result-newhome/attack/autoattack/preactresnet34-svhn/20220724/00000-autoattack-eps-0.1-acc-29.80/attack-svhn-dataset/samples/test --batch_size 256 --epochs 40 --lr 0.01 >> /home/maggie/mmat/log/SVHN/defense/manifold-mixup-training/preactresnet34-svhn-manifoldmixup-autoattack-20220916.log 2>&1

# # PreActResNet34 manifoldmixup beta(1,1) against deepfool (eps=0.1)
# CUDA_VISIBLE_DEVICES=0 python -u tasklauncher-20220905.py run --mode defense --defense_mode manifoldmixup --beta_alpha 1 --mix_mode basemixup --sample_mode betasampler --attack_mode deepfool --attack_eps 0.1 --blackbox --exp_name preactresnet34-svhn --cla_model preactresnet34 --cla_network_pkl /home/data/maggie/result-newhome/defense/manifoldmixup/fgsm/basemixup-betasampler/preactresnet34-svhn/blackbox/20220902/00006/manifoldmixup-svhn-dataset/manifoldmixup-trained-classifier-preactresnet34-on-svhn-epoch-0006manifoldmix-cla2.pkl --dataset svhn --test_adv_dataset /home/data/maggie/result-newhome/attack/deepfool/preactresnet34-svhn/20220720/00000-deepfool-eps-0.1-acc-19.94/attack-svhn-dataset/samples/test --batch_size 256 --epochs 40 --lr 0.01 >> /home/maggie/mmat/log/SVHN/defense/manifold-mixup-training/preactresnet34-svhn-manifoldmixup-deepfool-20220916.log 2>&1

# # PreActResNet34 manifoldmixup beta(1,1) against cw (eps=0.1)
# CUDA_VISIBLE_DEVICES=0 python -u tasklauncher-20220905.py run --mode defense --defense_mode manifoldmixup --beta_alpha 1 --mix_mode basemixup --sample_mode betasampler --attack_mode cw --attack_eps 0.1 --blackbox --exp_name preactresnet34-svhn --cla_model preactresnet34 --cla_network_pkl /home/data/maggie/result-newhome/defense/manifoldmixup/fgsm/basemixup-betasampler/preactresnet34-svhn/blackbox/20220902/00006/manifoldmixup-svhn-dataset/manifoldmixup-trained-classifier-preactresnet34-on-svhn-epoch-0006manifoldmix-cla2.pkl --dataset svhn --test_adv_dataset /home/data/maggie/result-newhome/attack/cw/preactresnet34-svhn/20220708/00000-cw-confidence-0.0-acc-25.62/attack-svhn-dataset/samples/test --batch_size 256 --epochs 40 --lr 0.01 >> /home/maggie/mmat/log/SVHN/defense/manifold-mixup-training/preactresnet34-svhn-manifoldmixup-cw-20220916.log 2>&1

# # PreActResNet34 manifoldmixup beta(1,1) against om-fgsm (eps=0.1)
# CUDA_VISIBLE_DEVICES=0 python -u tasklauncher-20220905.py run --mode defense --defense_mode manifoldmixup --beta_alpha 1 --mix_mode basemixup --sample_mode betasampler --attack_mode om-fgsm --attack_eps 0.1 --blackbox --exp_name preactresnet34-svhn --cla_model preactresnet34 --cla_network_pkl /home/data/maggie/result-newhome/defense/manifoldmixup/fgsm/basemixup-betasampler/preactresnet34-svhn/blackbox/20220902/00006/manifoldmixup-svhn-dataset/manifoldmixup-trained-classifier-preactresnet34-on-svhn-epoch-0006manifoldmix-cla2.pkl --dataset svhn --test_adv_dataset /home/data/maggie/result-newhome/attack/fgsm/preactresnet34-svhn/20220710/00002-omfgsm-eps-0.1-acc-36.62/attack-svhn-dataset/latent-attack-samples/test --batch_size 256 --epochs 40 --lr 0.01 >> /home/maggie/mmat/log/SVHN/defense/manifold-mixup-training/preactresnet34-svhn-manifoldmixup-om-fgsm-20220916.log 2>&1

# # PreActResNet34 manifoldmixup beta(1,1) against om-pgd (eps=0.1)
# CUDA_VISIBLE_DEVICES=0 python -u tasklauncher-20220905.py run --mode defense --defense_mode manifoldmixup --beta_alpha 1 --mix_mode basemixup --sample_mode betasampler --attack_mode om-pgd --attack_eps 0.1 --blackbox --exp_name preactresnet34-svhn --cla_model preactresnet34 --cla_network_pkl /home/data/maggie/result-newhome/defense/manifoldmixup/fgsm/basemixup-betasampler/preactresnet34-svhn/blackbox/20220902/00006/manifoldmixup-svhn-dataset/manifoldmixup-trained-classifier-preactresnet34-on-svhn-epoch-0006manifoldmix-cla2.pkl --dataset svhn --test_adv_dataset /home/data/maggie/result-newhome/attack/pgd/preactresnet34-svhn/20220712/00002-ompgd-eps-0.1-acc-5.01/attack-svhn-dataset/latent-attack-samples/test --batch_size 256 --epochs 40 --lr 0.01 >> /home/maggie/mmat/log/SVHN/defense/manifold-mixup-training/preactresnet34-svhn-manifoldmixup-om-pgd-20220916.log 2>&1

# #   使用PGD对抗训练后的 cla3
# PreActResNet34 manifoldmixup beta(1,1) against pgd (eps=0.1)
CUDA_VISIBLE_DEVICES=0 python -u tasklauncher-20220905.py run --mode defense --defense_mode manifoldmixup --beta_alpha 1 --mix_mode basemixup --sample_mode betasampler --attack_mode pgd --attack_eps 0.1 --blackbox --exp_name preactresnet34-svhn --cla_model preactresnet34 --cla_network_pkl /home/data/maggie/result-newhome/defense/manifoldmixup/fgsm/basemixup-betasampler/preactresnet34-svhn/blackbox/20220916/00001/manifoldmixup-svhn-dataset/manifoldmixup-trained-classifier-preactresnet34-on-svhn-epoch-0040-manifold-cla3.pkl --dataset svhn --test_adv_dataset /home/data/maggie/result-newhome/attack/pgd/preactresnet34-svhn/20220629/00002-pgd-eps-0.1-acc-35.57/attack-svhn-dataset/samples/test --batch_size 256 --epochs 40 --lr 0.01 >> /home/maggie/mmat/log/SVHN/defense/manifold-mixup-training/preactresnet34-svhn-manifoldmixup-pgd-20220916.log 2>&1

# PreActResNet34 manifoldmixup beta(1,1) against autoattack (eps=0.1)
CUDA_VISIBLE_DEVICES=0 python -u tasklauncher-20220905.py run --mode defense --defense_mode manifoldmixup --beta_alpha 1 --mix_mode basemixup --sample_mode betasampler --attack_mode autoattack --attack_eps 0.1 --blackbox --exp_name preactresnet34-svhn --cla_model preactresnet34 --cla_network_pkl /home/data/maggie/result-newhome/defense/manifoldmixup/fgsm/basemixup-betasampler/preactresnet34-svhn/blackbox/20220916/00001/manifoldmixup-svhn-dataset/manifoldmixup-trained-classifier-preactresnet34-on-svhn-epoch-0040-manifold-cla3.pkl --dataset svhn --test_adv_dataset /home/data/maggie/result-newhome/attack/autoattack/preactresnet34-svhn/20220724/00000-autoattack-eps-0.1-acc-29.80/attack-svhn-dataset/samples/test --batch_size 256 --epochs 40 --lr 0.01 >> /home/maggie/mmat/log/SVHN/defense/manifold-mixup-training/preactresnet34-svhn-manifoldmixup-autoattack-20220916.log 2>&1

# PreActResNet34 manifoldmixup beta(1,1) against deepfool (eps=0.1)
CUDA_VISIBLE_DEVICES=0 python -u tasklauncher-20220905.py run --mode defense --defense_mode manifoldmixup --beta_alpha 1 --mix_mode basemixup --sample_mode betasampler --attack_mode deepfool --attack_eps 0.1 --blackbox --exp_name preactresnet34-svhn --cla_model preactresnet34 --cla_network_pkl /home/data/maggie/result-newhome/defense/manifoldmixup/fgsm/basemixup-betasampler/preactresnet34-svhn/blackbox/20220916/00001/manifoldmixup-svhn-dataset/manifoldmixup-trained-classifier-preactresnet34-on-svhn-epoch-0040-manifold-cla3.pkl --dataset svhn --test_adv_dataset /home/data/maggie/result-newhome/attack/deepfool/preactresnet34-svhn/20220720/00000-deepfool-eps-0.1-acc-19.94/attack-svhn-dataset/samples/test --batch_size 256 --epochs 40 --lr 0.01 >> /home/maggie/mmat/log/SVHN/defense/manifold-mixup-training/preactresnet34-svhn-manifoldmixup-deepfool-20220916.log 2>&1

# PreActResNet34 manifoldmixup beta(1,1) against cw (eps=0.1)
CUDA_VISIBLE_DEVICES=0 python -u tasklauncher-20220905.py run --mode defense --defense_mode manifoldmixup --beta_alpha 1 --mix_mode basemixup --sample_mode betasampler --attack_mode cw --attack_eps 0.1 --blackbox --exp_name preactresnet34-svhn --cla_model preactresnet34 --cla_network_pkl /home/data/maggie/result-newhome/defense/manifoldmixup/fgsm/basemixup-betasampler/preactresnet34-svhn/blackbox/20220916/00001/manifoldmixup-svhn-dataset/manifoldmixup-trained-classifier-preactresnet34-on-svhn-epoch-0040-manifold-cla3.pkl --dataset svhn --test_adv_dataset /home/data/maggie/result-newhome/attack/cw/preactresnet34-svhn/20220708/00000-cw-confidence-0.0-acc-25.62/attack-svhn-dataset/samples/test --batch_size 256 --epochs 40 --lr 0.01 >> /home/maggie/mmat/log/SVHN/defense/manifold-mixup-training/preactresnet34-svhn-manifoldmixup-cw-20220916.log 2>&1

# PreActResNet34 manifoldmixup beta(1,1) against om-fgsm (eps=0.1)
CUDA_VISIBLE_DEVICES=0 python -u tasklauncher-20220905.py run --mode defense --defense_mode manifoldmixup --beta_alpha 1 --mix_mode basemixup --sample_mode betasampler --attack_mode om-fgsm --attack_eps 0.1 --blackbox --exp_name preactresnet34-svhn --cla_model preactresnet34 --cla_network_pkl /home/data/maggie/result-newhome/defense/manifoldmixup/fgsm/basemixup-betasampler/preactresnet34-svhn/blackbox/20220916/00001/manifoldmixup-svhn-dataset/manifoldmixup-trained-classifier-preactresnet34-on-svhn-epoch-0040-manifold-cla3.pkl --dataset svhn --test_adv_dataset /home/data/maggie/result-newhome/attack/fgsm/preactresnet34-svhn/20220710/00002-omfgsm-eps-0.1-acc-36.62/attack-svhn-dataset/latent-attack-samples/test --batch_size 256 --epochs 40 --lr 0.01 >> /home/maggie/mmat/log/SVHN/defense/manifold-mixup-training/preactresnet34-svhn-manifoldmixup-om-fgsm-20220916.log 2>&1

# PreActResNet34 manifoldmixup beta(1,1) against om-pgd (eps=0.1)
CUDA_VISIBLE_DEVICES=0 python -u tasklauncher-20220905.py run --mode defense --defense_mode manifoldmixup --beta_alpha 1 --mix_mode basemixup --sample_mode betasampler --attack_mode om-pgd --attack_eps 0.1 --blackbox --exp_name preactresnet34-svhn --cla_model preactresnet34 --cla_network_pkl /home/data/maggie/result-newhome/defense/manifoldmixup/fgsm/basemixup-betasampler/preactresnet34-svhn/blackbox/20220916/00001/manifoldmixup-svhn-dataset/manifoldmixup-trained-classifier-preactresnet34-on-svhn-epoch-0040-manifold-cla3.pkl --dataset svhn --test_adv_dataset /home/data/maggie/result-newhome/attack/pgd/preactresnet34-svhn/20220712/00002-ompgd-eps-0.1-acc-5.01/attack-svhn-dataset/latent-attack-samples/test --batch_size 256 --epochs 40 --lr 0.01 >> /home/maggie/mmat/log/SVHN/defense/manifold-mixup-training/preactresnet34-svhn-manifoldmixup-om-pgd-20220916.log 2>&1

# # #   使用PGD对抗训练后的 cla4
# # PreActResNet34 manifoldmixup beta(1,1) against pgd (eps=0.1)
# CUDA_VISIBLE_DEVICES=0 python -u tasklauncher-20220905.py run --mode defense --defense_mode manifoldmixup --beta_alpha 1 --mix_mode basemixup --sample_mode betasampler --attack_mode pgd --attack_eps 0.1 --blackbox --exp_name preactresnet34-svhn --cla_model preactresnet34 --cla_network_pkl XXX-cla4-XXX --dataset svhn --test_adv_dataset /home/data/maggie/result-newhome/attack/pgd/preactresnet34-svhn/20220629/00002-pgd-eps-0.1-acc-35.57/attack-svhn-dataset/samples/test --batch_size 256 --epochs 40 --lr 0.01 >> /home/maggie/mmat/log/SVHN/defense/manifold-mixup-training/preactresnet34-svhn-manifoldmixup-pgd-20220916.log 2>&1

# # PreActResNet34 manifoldmixup beta(1,1) against autoattack (eps=0.1)
# CUDA_VISIBLE_DEVICES=0 python -u tasklauncher-20220905.py run --mode defense --defense_mode manifoldmixup --beta_alpha 1 --mix_mode basemixup --sample_mode betasampler --attack_mode autoattack --attack_eps 0.1 --blackbox --exp_name preactresnet34-svhn --cla_model preactresnet34 --cla_network_pkl XXX-cla4-XXX --dataset svhn --test_adv_dataset /home/data/maggie/result-newhome/attack/autoattack/preactresnet34-svhn/20220724/00000-autoattack-eps-0.1-acc-29.80/attack-svhn-dataset/samples/test --batch_size 256 --epochs 40 --lr 0.01 >> /home/maggie/mmat/log/SVHN/defense/manifold-mixup-training/preactresnet34-svhn-manifoldmixup-autoattack-20220916.log 2>&1

# # PreActResNet34 manifoldmixup beta(1,1) against deepfool (eps=0.1)
# CUDA_VISIBLE_DEVICES=0 python -u tasklauncher-20220905.py run --mode defense --defense_mode manifoldmixup --beta_alpha 1 --mix_mode basemixup --sample_mode betasampler --attack_mode deepfool --attack_eps 0.1 --blackbox --exp_name preactresnet34-svhn --cla_model preactresnet34 --cla_network_pkl XXX-cla4-XXX --dataset svhn --test_adv_dataset /home/data/maggie/result-newhome/attack/deepfool/preactresnet34-svhn/20220720/00000-deepfool-eps-0.1-acc-19.94/attack-svhn-dataset/samples/test --batch_size 256 --epochs 40 --lr 0.01 >> /home/maggie/mmat/log/SVHN/defense/manifold-mixup-training/preactresnet34-svhn-manifoldmixup-deepfool-20220916.log 2>&1

# # PreActResNet34 manifoldmixup beta(1,1) against cw (eps=0.1)
# CUDA_VISIBLE_DEVICES=0 python -u tasklauncher-20220905.py run --mode defense --defense_mode manifoldmixup --beta_alpha 1 --mix_mode basemixup --sample_mode betasampler --attack_mode cw --attack_eps 0.1 --blackbox --exp_name preactresnet34-svhn --cla_model preactresnet34 --cla_network_pkl XXX-cla4-XXX --dataset svhn --test_adv_dataset /home/data/maggie/result-newhome/attack/cw/preactresnet34-svhn/20220708/00000-cw-confidence-0.0-acc-25.62/attack-svhn-dataset/samples/test --batch_size 256 --epochs 40 --lr 0.01 >> /home/maggie/mmat/log/SVHN/defense/manifold-mixup-training/preactresnet34-svhn-manifoldmixup-cw-20220916.log 2>&1

# # PreActResNet34 manifoldmixup beta(1,1) against om-fgsm (eps=0.1)
# CUDA_VISIBLE_DEVICES=0 python -u tasklauncher-20220905.py run --mode defense --defense_mode manifoldmixup --beta_alpha 1 --mix_mode basemixup --sample_mode betasampler --attack_mode om-fgsm --attack_eps 0.1 --blackbox --exp_name preactresnet34-svhn --cla_model preactresnet34 --cla_network_pkl XXX-cla4-XXX --dataset svhn --test_adv_dataset /home/data/maggie/result-newhome/attack/fgsm/preactresnet34-svhn/20220710/00002-omfgsm-eps-0.1-acc-36.62/attack-svhn-dataset/latent-attack-samples/test --batch_size 256 --epochs 40 --lr 0.01 >> /home/maggie/mmat/log/SVHN/defense/manifold-mixup-training/preactresnet34-svhn-manifoldmixup-om-fgsm-20220916.log 2>&1

# # PreActResNet34 manifoldmixup beta(1,1) against om-pgd (eps=0.1)
# CUDA_VISIBLE_DEVICES=0 python -u tasklauncher-20220905.py run --mode defense --defense_mode manifoldmixup --beta_alpha 1 --mix_mode basemixup --sample_mode betasampler --attack_mode om-pgd --attack_eps 0.1 --blackbox --exp_name preactresnet34-svhn --cla_model preactresnet34 --cla_network_pkl XXX-cla4-XXX --dataset svhn --test_adv_dataset /home/data/maggie/result-newhome/attack/pgd/preactresnet34-svhn/20220712/00002-ompgd-eps-0.1-acc-5.01/attack-svhn-dataset/latent-attack-samples/test --batch_size 256 --epochs 40 --lr 0.01 >> /home/maggie/mmat/log/SVHN/defense/manifold-mixup-training/preactresnet34-svhn-manifoldmixup-om-pgd-20220916.log 2>&1

# # #   使用PGD对抗训练后的 cla5
# # PreActResNet34 manifoldmixup beta(1,1) against pgd (eps=0.1)
# CUDA_VISIBLE_DEVICES=0 python -u tasklauncher-20220905.py run --mode defense --defense_mode manifoldmixup --beta_alpha 1 --mix_mode basemixup --sample_mode betasampler --attack_mode pgd --attack_eps 0.1 --blackbox --exp_name preactresnet34-svhn --cla_model preactresnet34 --cla_network_pkl XXX-cla5-XXX --dataset svhn --test_adv_dataset /home/data/maggie/result-newhome/attack/pgd/preactresnet34-svhn/20220629/00002-pgd-eps-0.1-acc-35.57/attack-svhn-dataset/samples/test --batch_size 256 --epochs 40 --lr 0.01 >> /home/maggie/mmat/log/SVHN/defense/manifold-mixup-training/preactresnet34-svhn-manifoldmixup-pgd-20220916.log 2>&1

# # PreActResNet34 manifoldmixup beta(1,1) against autoattack (eps=0.1)
# CUDA_VISIBLE_DEVICES=0 python -u tasklauncher-20220905.py run --mode defense --defense_mode manifoldmixup --beta_alpha 1 --mix_mode basemixup --sample_mode betasampler --attack_mode autoattack --attack_eps 0.1 --blackbox --exp_name preactresnet34-svhn --cla_model preactresnet34 --cla_network_pkl XXX-cla5-XXX --dataset svhn --test_adv_dataset /home/data/maggie/result-newhome/attack/autoattack/preactresnet34-svhn/20220724/00000-autoattack-eps-0.1-acc-29.80/attack-svhn-dataset/samples/test --batch_size 256 --epochs 40 --lr 0.01 >> /home/maggie/mmat/log/SVHN/defense/manifold-mixup-training/preactresnet34-svhn-manifoldmixup-autoattack-20220916.log 2>&1

# # PreActResNet34 manifoldmixup beta(1,1) against deepfool (eps=0.1)
# CUDA_VISIBLE_DEVICES=0 python -u tasklauncher-20220905.py run --mode defense --defense_mode manifoldmixup --beta_alpha 1 --mix_mode basemixup --sample_mode betasampler --attack_mode deepfool --attack_eps 0.1 --blackbox --exp_name preactresnet34-svhn --cla_model preactresnet34 --cla_network_pkl XXX-cla5-XXX --dataset svhn --test_adv_dataset /home/data/maggie/result-newhome/attack/deepfool/preactresnet34-svhn/20220720/00000-deepfool-eps-0.1-acc-19.94/attack-svhn-dataset/samples/test --batch_size 256 --epochs 40 --lr 0.01 >> /home/maggie/mmat/log/SVHN/defense/manifold-mixup-training/preactresnet34-svhn-manifoldmixup-deepfool-20220916.log 2>&1

# # PreActResNet34 manifoldmixup beta(1,1) against cw (eps=0.1)
# CUDA_VISIBLE_DEVICES=0 python -u tasklauncher-20220905.py run --mode defense --defense_mode manifoldmixup --beta_alpha 1 --mix_mode basemixup --sample_mode betasampler --attack_mode cw --attack_eps 0.1 --blackbox --exp_name preactresnet34-svhn --cla_model preactresnet34 --cla_network_pkl XXX-cla5-XXX --dataset svhn --test_adv_dataset /home/data/maggie/result-newhome/attack/cw/preactresnet34-svhn/20220708/00000-cw-confidence-0.0-acc-25.62/attack-svhn-dataset/samples/test --batch_size 256 --epochs 40 --lr 0.01 >> /home/maggie/mmat/log/SVHN/defense/manifold-mixup-training/preactresnet34-svhn-manifoldmixup-cw-20220916.log 2>&1

# # PreActResNet34 manifoldmixup beta(1,1) against om-fgsm (eps=0.1)
# CUDA_VISIBLE_DEVICES=0 python -u tasklauncher-20220905.py run --mode defense --defense_mode manifoldmixup --beta_alpha 1 --mix_mode basemixup --sample_mode betasampler --attack_mode om-fgsm --attack_eps 0.1 --blackbox --exp_name preactresnet34-svhn --cla_model preactresnet34 --cla_network_pkl XXX-cla5-XXX --dataset svhn --test_adv_dataset /home/data/maggie/result-newhome/attack/fgsm/preactresnet34-svhn/20220710/00002-omfgsm-eps-0.1-acc-36.62/attack-svhn-dataset/latent-attack-samples/test --batch_size 256 --epochs 40 --lr 0.01 >> /home/maggie/mmat/log/SVHN/defense/manifold-mixup-training/preactresnet34-svhn-manifoldmixup-om-fgsm-20220916.log 2>&1

# # PreActResNet34 manifoldmixup beta(1,1) against om-pgd (eps=0.1)
# CUDA_VISIBLE_DEVICES=0 python -u tasklauncher-20220905.py run --mode defense --defense_mode manifoldmixup --beta_alpha 1 --mix_mode basemixup --sample_mode betasampler --attack_mode om-pgd --attack_eps 0.1 --blackbox --exp_name preactresnet34-svhn --cla_model preactresnet34 --cla_network_pkl XXX-cla5-XXX --dataset svhn --test_adv_dataset /home/data/maggie/result-newhome/attack/pgd/preactresnet34-svhn/20220712/00002-ompgd-eps-0.1-acc-5.01/attack-svhn-dataset/latent-attack-samples/test --batch_size 256 --epochs 40 --lr 0.01 >> /home/maggie/mmat/log/SVHN/defense/manifold-mixup-training/preactresnet34-svhn-manifoldmixup-om-pgd-20220916.log 2>&1

# # #   使用PGD对抗训练后的 cla6
# # PreActResNet34 manifoldmixup beta(1,1) against pgd (eps=0.1)
# CUDA_VISIBLE_DEVICES=0 python -u tasklauncher-20220905.py run --mode defense --defense_mode manifoldmixup --beta_alpha 1 --mix_mode basemixup --sample_mode betasampler --attack_mode pgd --attack_eps 0.1 --blackbox --exp_name preactresnet34-svhn --cla_model preactresnet34 --cla_network_pkl XXX-cla6-XXX --dataset svhn --test_adv_dataset /home/data/maggie/result-newhome/attack/pgd/preactresnet34-svhn/20220629/00002-pgd-eps-0.1-acc-35.57/attack-svhn-dataset/samples/test --batch_size 256 --epochs 40 --lr 0.01 >> /home/maggie/mmat/log/SVHN/defense/manifold-mixup-training/preactresnet34-svhn-manifoldmixup-pgd-20220916.log 2>&1

# # PreActResNet34 manifoldmixup beta(1,1) against autoattack (eps=0.1)
# CUDA_VISIBLE_DEVICES=0 python -u tasklauncher-20220905.py run --mode defense --defense_mode manifoldmixup --beta_alpha 1 --mix_mode basemixup --sample_mode betasampler --attack_mode autoattack --attack_eps 0.1 --blackbox --exp_name preactresnet34-svhn --cla_model preactresnet34 --cla_network_pkl XXX-cla6-XXX --dataset svhn --test_adv_dataset /home/data/maggie/result-newhome/attack/autoattack/preactresnet34-svhn/20220724/00000-autoattack-eps-0.1-acc-29.80/attack-svhn-dataset/samples/test --batch_size 256 --epochs 40 --lr 0.01 >> /home/maggie/mmat/log/SVHN/defense/manifold-mixup-training/preactresnet34-svhn-manifoldmixup-autoattack-20220916.log 2>&1

# # PreActResNet34 manifoldmixup beta(1,1) against deepfool (eps=0.1)
# CUDA_VISIBLE_DEVICES=0 python -u tasklauncher-20220905.py run --mode defense --defense_mode manifoldmixup --beta_alpha 1 --mix_mode basemixup --sample_mode betasampler --attack_mode deepfool --attack_eps 0.1 --blackbox --exp_name preactresnet34-svhn --cla_model preactresnet34 --cla_network_pkl XXX-cla6-XXX --dataset svhn --test_adv_dataset /home/data/maggie/result-newhome/attack/deepfool/preactresnet34-svhn/20220720/00000-deepfool-eps-0.1-acc-19.94/attack-svhn-dataset/samples/test --batch_size 256 --epochs 40 --lr 0.01 >> /home/maggie/mmat/log/SVHN/defense/manifold-mixup-training/preactresnet34-svhn-manifoldmixup-deepfool-20220916.log 2>&1

# # PreActResNet34 manifoldmixup beta(1,1) against cw (eps=0.1)
# CUDA_VISIBLE_DEVICES=0 python -u tasklauncher-20220905.py run --mode defense --defense_mode manifoldmixup --beta_alpha 1 --mix_mode basemixup --sample_mode betasampler --attack_mode cw --attack_eps 0.1 --blackbox --exp_name preactresnet34-svhn --cla_model preactresnet34 --cla_network_pkl XXX-cla6-XXX --dataset svhn --test_adv_dataset /home/data/maggie/result-newhome/attack/cw/preactresnet34-svhn/20220708/00000-cw-confidence-0.0-acc-25.62/attack-svhn-dataset/samples/test --batch_size 256 --epochs 40 --lr 0.01 >> /home/maggie/mmat/log/SVHN/defense/manifold-mixup-training/preactresnet34-svhn-manifoldmixup-cw-20220916.log 2>&1

# # PreActResNet34 manifoldmixup beta(1,1) against om-fgsm (eps=0.1)
# CUDA_VISIBLE_DEVICES=0 python -u tasklauncher-20220905.py run --mode defense --defense_mode manifoldmixup --beta_alpha 1 --mix_mode basemixup --sample_mode betasampler --attack_mode om-fgsm --attack_eps 0.1 --blackbox --exp_name preactresnet34-svhn --cla_model preactresnet34 --cla_network_pkl XXX-cla6-XXX --dataset svhn --test_adv_dataset /home/data/maggie/result-newhome/attack/fgsm/preactresnet34-svhn/20220710/00002-omfgsm-eps-0.1-acc-36.62/attack-svhn-dataset/latent-attack-samples/test --batch_size 256 --epochs 40 --lr 0.01 >> /home/maggie/mmat/log/SVHN/defense/manifold-mixup-training/preactresnet34-svhn-manifoldmixup-om-fgsm-20220916.log 2>&1

# # PreActResNet34 manifoldmixup beta(1,1) against om-pgd (eps=0.1)
# CUDA_VISIBLE_DEVICES=0 python -u tasklauncher-20220905.py run --mode defense --defense_mode manifoldmixup --beta_alpha 1 --mix_mode basemixup --sample_mode betasampler --attack_mode om-pgd --attack_eps 0.1 --blackbox --exp_name preactresnet34-svhn --cla_model preactresnet34 --cla_network_pkl XXX-cla6-XXX --dataset svhn --test_adv_dataset /home/data/maggie/result-newhome/attack/pgd/preactresnet34-svhn/20220712/00002-ompgd-eps-0.1-acc-5.01/attack-svhn-dataset/latent-attack-samples/test --batch_size 256 --epochs 40 --lr 0.01 >> /home/maggie/mmat/log/SVHN/defense/manifold-mixup-training/preactresnet34-svhn-manifoldmixup-om-pgd-20220916.log 2>&1